feat-new-image-features
appwrite/appwrite pull request #1008
Opened 2021-03-22 06:55 UTC by lohanidamodar

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2021-03-23 08:34 UTC, eldadfux commented
@lohanidamodar I think the tests are failing on the storage endpoints.

2021-03-24 05:15 UTC, lohanidamodar commented
@eldadfux the Tests are passing in Branch but failing in PR not sure. Do you need to re-run? Let me know

2021-03-24 06:30 UTC, eldadfux commented
@lohanidamodar I restarted the tests. Please note, we need e2e tests here to validate the API endpoint behavior.

2021-03-26 10:28 UTC, lohanidamodar commented
@eldadfux please restart the tests

2021-03-29 17:55 UTC, christyjacob4 commented on app/controllers/api/storage.php
> +    ->param('borderWidth', 0, new Range(0, 100), 'Preview image border. Pass an integer between 0 to 100. Defaults to 0.', true)
```suggestion
    ->param('borderWidth', 0, new Range(0, 100), 'Preview image border in pixels. Pass an integer between 0 to 100. Defaults to 0.', true)
```
Might be more clear

2021-03-29 17:56 UTC, christyjacob4 commented on app/controllers/api/storage.php
> +    ->param('borderColor', '', new HexColor(), 'Preview image border color. Use a valid HEX color, no # is needed for prefix.', true)
```suggestion
    ->param('borderColor', '', new HexColor(), 'Preview image border color. Use a valid HEX color, # prefix is optional', true)
```

2021-03-29 17:56 UTC, christyjacob4 commented on app/controllers/api/storage.php
> +    ->param('borderRadius', 0, new Range(0, 4000), 'Preview image border radius. Pass an integer between 0 to 4000.', true)
```suggestion
    ->param('borderRadius', 0, new Range(0, 4000), 'Preview image border radius in pixels. Pass an integer between 0 to 4000.', true)
```

2021-03-29 17:57 UTC, christyjacob4 commented on app/controllers/api/storage.php
> +    ->param('opacity', 1, new Range(0,1), 'Preview image opacity. Only works with transparent images (png). Pass an integer between 0 to 1.', true)
```suggestion
    ->param('opacity', 1, new Range(0,1), 'Preview image opacity. Only works with transparent images (png). Pass a number between 0 to 1.', true)
```

2021-03-29 17:58 UTC, christyjacob4 commented on app/controllers/api/storage.php
> +    ->param('rotation', 0, new Range(0,360), 'Preview image rotation. Pass an integer between 0 to 360.', true)
```suggestion
    ->param('rotation', 0, new Range(0,360), 'Preview image rotation in degrees. Pass an integer between 0 and 360.', true)
```

2021-03-29 18:02 UTC, christyjacob4 requested changes
Looks Good @lohanidamodar  . Some minor suggestions

2021-04-02 05:22 UTC, eldadfux commented
@lohanidamodar when @christyjacob4 are addressed we can merge this PR to 0.8

2021-04-07 01:38 UTC, lohanidamodar commented
@eldadfux This should be ready!

2021-04-09 07:10 UTC, lohanidamodar commented
@eldadfux pushed small fix for border with border radius issue. Need the newer version of utopia-php/image released with the latest PR merged.

2021-04-13 20:23 UTC, eldadfux commented
@lohanidamodar we need to make sure the PR is using https://github.com/utopia-php/image v0.2.1

2021-04-15 06:11 UTC, lohanidamodar commented
> @lohanidamodar we need to make sure the PR is using https://github.com/utopia-php/image v0.2.1

@eldadfux done

2021-04-15 06:37 UTC, eldadfux commented
@christyjacob4 if you're OK we can merge.

2021-04-15 12:43 UTC, christyjacob4 approved these changes
Looks Good @lohanidamodar

2021-04-15 12:48 UTC, merged