feat-android-platform
appwrite/appwrite pull request #1093
Opened 2021-04-16 08:57 UTC by lohanidamodar

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2021-04-16 09:02 UTC, eldadfux commented
@lohanidamodar please post some screenshot and verify the update functionality is working as expected

2021-04-16 09:26 UTC, lohanidamodar commented
Here's a preview
![2021-04-16_14-35](https://user-images.githubusercontent.com/6360216/115003739-d4bf8800-9ec5-11eb-
9c16-b3a92bc55f1c.png)

@eldadfux The updates are working fine as well

2021-04-16 21:17 UTC, eldadfux requested changes

2021-04-16 21:17 UTC, eldadfux commented on app/views/console/home/index.phtml
> +            <li>
Let's move the Android app above the `coming soon` platforms

2021-04-19 20:14 UTC, eldadfux approved these changes

2021-06-02 17:18 UTC, merged