feat-automated-install
appwrite/appwrite pull request #1139
Opened 2021-05-12 08:12 UTC by lohanidamodar

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2021-05-13 04:00 UTC, eldadfux approved these changes

2021-05-13 09:26 UTC, TorstenDittmann requested changes

2021-05-13 09:26 UTC, TorstenDittmann commented on app/tasks/install.php
> +    ->param('interactive','Y', new Text(1), 'A secure encryption key, make sure to make a backup of your key in a secure location')
I think the description is wrong here 🙂

2021-05-14 06:58 UTC, eldadfux commented on app/tasks/install.php
> +    ->param('interactive','Y', new Text(1), 'Run a interactive session', true)
```suggestion
    ->param('interactive','Y', new Text(1), 'Run an interactive session', true)
```

2021-05-14 06:58 UTC, merged