feat-service-flags
appwrite/appwrite pull request #1211
Opened 2021-05-28 11:16 UTC by lohanidamodar

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2021-05-28 12:36 UTC, mochaelphilip672 approved these changes

2021-05-28 12:43 UTC, mochaelphilip672 commented
Protect me more

2021-06-02 07:16 UTC, eldadfux requested changes

2021-06-02 07:16 UTC, eldadfux commented on src/Appwrite/Utopia/Response/Model/Project.php
> +            ->addRule('services', [
Not sure about this structure, I would try to avoid nested objects, maybe we can have a key per service where the default value is `true`?

2021-06-02 07:16 UTC, eldadfux commented on app/controllers/general.php
> +            throw new Exception('Service Disabled', 503);
```suggestion
            throw new Exception('Service is disabled', 503);
```

2021-06-02 07:16 UTC, eldadfux commented on app/controllers/api/projects.php
> +    ->desc('Update service flags')
```suggestion
    ->desc('Update service status')
```

2021-06-02 07:16 UTC, eldadfux commented on app/controllers/api/projects.php
> +    ->param('service', '', new WhiteList(["functions","webhooks","avatars","health","locale","storage","teams"],true), 'Service to change status of.')
Do we have any config array we can use for this list?

2021-06-02 07:16 UTC, eldadfux commented on app/controllers/api/projects.php
> +    ->param('service', '', new WhiteList(["functions","webhooks","avatars","health","locale","storage","teams"],true), 'Service to change status of.')
Always prefer single quotes `'` over `"`

2021-06-02 07:16 UTC, eldadfux commented on app/controllers/api/projects.php
> +    ->param('service', '', new WhiteList(["functions","webhooks","avatars","health","locale","storage","teams"],true), 'Service to change status of.')
```suggestion
    ->param('service', '', new WhiteList(["functions","webhooks","avatars","health","locale","storage","teams"],true), 'Service name.')
```

2021-06-03 09:57 UTC, TorstenDittmann reviewed
As discussed on Discord - the naming for the services in the Collection must be different and more grouped 🙂

2021-06-03 09:57 UTC, TorstenDittmann commented on app/controllers/api/projects.php
> +use Utopia\CLI\Console;
I don't think we need this import here 🙂

2021-06-09 13:12 UTC, eldadfux requested changes
The new param should be in camelCase. Meaning `statusForfunctions` should be `statusForFunctions`

2021-06-09 13:12 UTC, eldadfux commented on tests/e2e/Services/Projects/ProjectsConsoleClientTest.php
> +        $services = ['functions','webhooks', 'avatars','health','locale','storage','teams'];
```suggestion
        $services = ['functions', 'webhooks', 'avatars', 'health', 'locale', 'storage', 'teams'];
```

2021-06-10 08:55 UTC, PineappleIOnic approved these changes

2021-07-03 07:07 UTC, eldadfux approved these changes

2021-07-05 08:09 UTC, PineappleIOnic approved these changes

2021-07-05 08:43 UTC, TorstenDittmann approved these changes

2021-07-29 10:58 UTC, lohanidamodar commented
@eldadfux closing this in favor of #1446

2021-07-29 10:58 UTC, closed without merging