fix: ignore email case when creating account
appwrite/appwrite pull request #1243
Opened 2021-06-03 13:04 UTC by christyjacob4

## What does this PR do?
Emails are case insensitive. Ignore email case across all APIs

## Test Plan
Leverage Existing tests

## Related PRs and Issues
#1240 

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
Yes

2021-06-03 13:06 UTC, TorstenDittmann requested changes

2021-06-03 13:06 UTC, TorstenDittmann commented on app/controllers/api/account.php
> +            var_dump($whitelistEmails);
Missed that `var_dump`

2021-06-03 13:31 UTC, christyjacob4 commented on app/controllers/api/account.php
> +            var_dump($whitelistEmails);
fixed it :)

2021-06-03 14:06 UTC, TorstenDittmann commented
iirc, there is also an endpoint for teams where we use an e-mail.

2021-06-04 05:41 UTC, eldadfux approved these changes

2021-06-04 08:21 UTC, TorstenDittmann approved these changes

2021-06-07 20:57 UTC, merged