First Draft
appwrite/appwrite pull request #1277
Opened 2021-06-11 14:58 UTC by PineappleIOnic

## What does this PR do?
This PR Introduces the ability to name function tags to be more easily identifiable.

## Test Plan

I have added a new name field to tags, I have also implemented the relevant tests to ensure this is working as expected.

## Related PRs and Issues
https://github.com/appwrite/appwrite/issues/1222

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
Yes

2021-06-14 11:32 UTC, eldadfux requested changes

2021-06-14 11:32 UTC, eldadfux commented on app/controllers/api/functions.php
> +    ->param('name', '', new Text(512), 'Function Name', true)
I would probably have the name as the first param here.

2021-06-14 11:32 UTC, eldadfux commented on src/Appwrite/Utopia/Response/Model/Tag.php
> +            ->addRule('name', [
I would move the name above `command`

2021-06-14 11:32 UTC, eldadfux commented on src/Appwrite/Utopia/Response/Model/Tag.php
> +                'example' => 'Hello World Script',
```suggestion
                'example' => 'Hello World Tag',
```

2021-07-03 06:38 UTC, eldadfux commented
Waiting for progress on the [Custom IDs](https://github.com/appwrite/rfc/pull/26) RFC which might affect this breaking change.

2022-03-25 09:56 UTC, PineappleIOnic commented
Is this still a active PR or should I close it? @eldadfux

2022-06-03 10:28 UTC, closed without merging