feat-usage-daemon
appwrite/appwrite pull request #1481
Opened 2021-08-12 05:56 UTC by lohanidamodar

## What does this PR do?

Introduces a Usage daemon that syncs the data from InfluxDB to Appwrite's stats collection for each project

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

YES

2021-08-12 10:09 UTC, TorstenDittmann commented on app/workers.php
> +});
We might wanna move this to the `usage.php`, since its only used there and in no other worker.

2021-08-12 10:37 UTC, TorstenDittmann commented on app/tasks/usage.php
> +            $doc = $dbForProject->find('stats', [new Query("period", Query::TYPE_EQUAL, ["1d"])], 1, 0, ['time'], [Database::ORDER_DESC]);
You can try to use `findOne`. Then you don't need the `reset` anymore.

2021-08-13 06:22 UTC, eldadfux requested changes

2021-08-13 06:22 UTC, eldadfux commented on docker-compose.yml
> +  appwrite-usage:
This change should also be synced to compose.phtml file

2021-08-13 06:22 UTC, eldadfux commented on app/tasks/usage.php
> +require_once __DIR__ . '/../workers.php';
As this is not a worker, I think we should avoid using the workers init file.

2021-08-15 08:37 UTC, eldadfux commented on app/views/install/compose.phtml
> +      - _APP_USAGE_SYNC_INTERVAL
```suggestion
      - _APP_USAGE_AGGREGATION_INTERVAL
```

2021-08-15 08:37 UTC, eldadfux commented on app/views/install/compose.phtml
> +      - _APP_USAGE_SYNC_INTERVAL
This new var should also be documented

2021-08-19 05:30 UTC, merged