Feat decouple collections
appwrite/appwrite pull request #1499
Opened 2021-08-18 19:39 UTC by eldadfux

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2021-08-22 17:28 UTC, eldadfux commented on app/controllers/api/database.php
> +            break;
```suggestion
```

2021-08-22 17:28 UTC, eldadfux commented on app/workers/database.php
> +            $dbForInternal->updateDocument('attributes', $attribute->getId(), $attribute->setAttribute('status', 'failed'));
Maybe add an error description.

2021-08-23 14:28 UTC, kodumbeats requested changes

2021-08-23 20:41 UTC, eldadfux commented on app/controllers/api/database.php
> +    $default = (empty($default)) ? null : (int)$default;
Not resolved yet, need to find a way to save proper type for each attribute

2021-08-23 21:26 UTC, merged