Feat: enable SMTP debugging when not in production
appwrite/appwrite pull request #1644
Opened 2021-09-21 02:02 UTC by kodumbeats

## What does this PR do?

PHPMailer doesn't have very useful error messages by default, and in fact provides a [URL to their wiki](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting). This PR increases the debugging level of PHPMailer when not in production.

## Test Plan

Check logs on failed SMTP delivery.

## Related PRs and Issues

https://github.com/appwrite/appwrite/issues/1390

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes.

2021-11-02 15:37 UTC, TorstenDittmann approved these changes

2021-12-13 06:24 UTC, eldadfux requested changes

2021-12-13 06:24 UTC, eldadfux commented on app/workers/mails.php
> +        if (App::getEnv('_APP_ENV') !== App::MODE_TYPE_PRODUCTION) {
This method makes more sense to me: https://github.com/utopia-php/framework/blob/master/src/App.php#L411
I would just double check we initialize the env setting in the worker scope the same way we do for the REST API.

2023-08-31 01:50 UTC, stnguyen90 commented
@kodumbeats this is quite stale now and we've decided on a [different approach](https://github.com/appwrite/appwrite/issues/1390#issuecomment-1430273185) for debugging. As such, can this be closed?

2023-09-10 15:53 UTC, closed without merging