feat(translations): add french
appwrite/appwrite pull request #1771
Opened 2021-09-29 11:24 UTC by Olyno

## What does this PR do?

This pull request introduces the french translation.

## Test Plan

/

## Related PRs and Issues

#1687 

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes i did

2021-10-01 14:38 UTC, Stig124 approved these changes
`Salut` is not that formal, maybe `Bonjour/Bonsoir` would be more appropriate, approving the rest !

2021-10-01 15:13 UTC, Stig124 approved these changes

2021-10-04 12:44 UTC, christyjacob4 requested changes

2021-10-04 12:44 UTC, christyjacob4 commented on app/config/locale/terms.json
> +        "comment": "Ces noms de pays sont utilisés dans l'API Locale d'Appwrite. Pour en savoir plus, consultez le site https://appwrite.io/docs/client/locale#localeGetCountries.",
You don't need to modify this file as part of the PR. :slightly_smiling_face:  You can revert this change

2021-10-04 12:44 UTC, christyjacob4 commented on app/config/locale/translations/fr.json
> +    "emails.magicSession.hello": "Bonjour",
Please use the same punctuation as seen in the English translation https://github.com/appwrite/appwrite/blob/master/app/config/locale/translations/en.json#L13

2021-10-05 09:33 UTC, christyjacob4 approved these changes

2021-10-05 09:33 UTC, merged

2021-10-05 09:33 UTC, christyjacob4 commented
THANK YOU so much! All changes merged 🥳
Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swag!