chore: update the korean translation
appwrite/appwrite pull request #1814
Opened 2021-10-01 11:28 UTC by ssong

## What does this PR do?

Adds new email template translations for Korean and fixes the name for DRC.

Note: had to improvise a bit on `"emails.invitation.subject": "초대장 %s 팀 - %s",` as based on the string parsing order there wasn't really a nice sounding grammatically correct translation. So the translation for the subject currently reads `Invitation %s team - %s`

## Test Plan

Followed @christyjacob4 instructions

```
You can run Appwrite locally and run the e2e tests for the Teams or Accounts service. This will send the emails to the maildev server at localhost:9503
```

## Related PRs and Issues

fixes #1700 

### Have you read the [Contributing Guidelines on issues]

Yes

2021-10-04 14:12 UTC, christyjacob4 commented on app/config/locale/translations/ko.json
> +    "emails.invitation.hello": "안녕하세요",
```suggestion
    "emails.invitation.hello": "안녕하세요,",
```
Can we make sure punctuation is taken care of in all the strings ?
https://github.com/appwrite/appwrite/blob/master/app/config/locale/translations/en.json#L25

2021-10-04 14:13 UTC, christyjacob4 requested changes
Please address the comments

2021-10-04 14:47 UTC, christyjacob4 commented
I think I made an incorrect reference in my previous comment. Your PR looks good :+1:

2021-10-04 14:47 UTC, christyjacob4 approved these changes

2021-10-05 05:50 UTC, merged

2021-10-05 05:51 UTC, eldadfux commented
@ssong THANK YOU! All changes merged 🥳 🇰🇷

Please reach out to me (`eldadfux`) on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! 

As a way of saying thank you, we have just invited you to join the Appwrite organization on GitHub. You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) to help make Appwrite better.

2021-10-05 05:51 UTC, eldadfux commented
Thanks for helping @christyjacob4 🙏