Add spanish latin translation
appwrite/appwrite pull request #1830
Opened 2021-10-01 20:57 UTC by fernandoamz

## What does this PR do?
Add translation and files to load Spanish Lat.

## Test Plan
Someone who can run the project should make a checkout to review if the files and translations for Spanish lat are running correctly.

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2021-10-04 18:29 UTC, christyjacob4 commented on app/config/locale/translations/la.json
> +  "emails.invitation.body": "Este correo electrónico te fue enviado por que el dueño del proyecto quiere invitarte a convertirte en miembro en el equipo {{team}} en el {{project}}",
https://github.com/appwrite/appwrite/blob/master/app/config/locale/translations/en.json#L26

You're missing the `{{owner}}` placeholder

2021-10-04 18:30 UTC, christyjacob4 requested changes
Please address the comments

2021-10-04 18:32 UTC, christyjacob4 commented
It looks like you have translated this to Spanish. Whereas the issue was to translate it to Latin `la` .

2021-10-04 19:06 UTC, fernandoamz commented
Hey @christyjacob4, Sorry for confusing I thought it was Spanish Latino, I am doing the translation to Latin, I will push the new changes in a few moments.

2021-10-05 09:07 UTC, christyjacob4 commented
Sure! All the best :+1:

2021-10-06 03:47 UTC, closed without merging