Added Kannada translations
appwrite/appwrite pull request #1840
Opened 2021-10-02 08:57 UTC by Nikhil-1503

## What does this PR do?

This PR includes translations for Kannada language.

## Test Plan

Followed steps as mentioned in https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md#4-test-the-translations

## Related PRs and Issues

Fixes #1699 

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes, I have.

2021-10-02 14:49 UTC, spielers commented
Hey @Nikhil-1503
Thanks for your contribution!!!,
will get you merged ASAP  😇

Best,
suraj

2021-10-05 09:56 UTC, christyjacob4 requested changes

2021-10-05 09:56 UTC, christyjacob4 commented on app/config/locale/translations/kn.json
> +    "emails.invitation.subject": "%s ತಂಡಕ್ಕೆ %sರಲ್ಲಿ ಆಹ್ವಾನ",
```suggestion
    "emails.invitation.subject": "%s ತಂಡಕ್ಕೆ %s ರಲ್ಲಿ ಆಹ್ವಾನ",
```

Please ensure the spaces, and punctuation are exactly the same as `en.json`

2021-10-05 14:42 UTC, merged

2021-10-05 14:42 UTC, christyjacob4 commented
THANK YOU so much! All changes merged 🥳
Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swag!