Add Hebrew translation
appwrite/appwrite pull request #1846
Opened 2021-10-02 14:53 UTC by Kokoden

## What does this PR do?

Provides missing Hebrew translations.  I changed the inspiration quote to "To be wise is to know when to overlook" since it sounds more natural in Hebrew, let me know if you want me to change that :)

## Related PRs and Issues

Resolves #1689

2021-10-02 15:03 UTC, eldadfux requested changes
Thanks for your PR! (and finally a translation I can read 😅)

I suggested a few fixes, please review them 🙏🏻

2021-10-02 15:03 UTC, eldadfux commented on app/config/locale/translations/he.json
> +    "settings.inspire": "\"להיות חכם זה לדעת מתי להתעלם.\"",
```suggestion
    "settings.inspire": "\"להיות חכם זה לדעת ממה להתעלם.\"",
```

2021-10-02 15:03 UTC, eldadfux commented on app/config/locale/translations/he.json
> +    "emails.invitation.body": "דואר זה נשלח אליך מכיוון ש {{owner}} רצה להזמין אותך להיות חבר בצוות {{team}} ב- {{project}}.",
```suggestion
    "emails.invitation.body": "דואר זה נשלח אליך מכיוון ש {{owner}} רצה להזמין אותך להיות חבר בצוות {{team}} ב-{{project}}.",
```

2021-10-02 15:03 UTC, eldadfux commented on app/config/locale/translations/he.json
> +    "emails.recovery.body": "עקוב אחר קישור זה כדי לאפס את סיסמת הפרויקט {{project}}.",
```suggestion
    "emails.recovery.body": "עקוב אחר קישור זה כדי לאפס את סיסמתך ב-{{project}}.",
```

2021-10-02 21:55 UTC, Kokoden commented
Always happy to see a fellow Hebrew speaker haha. I applied the changes you suggested, let me know if you need anything else fixed.

2021-10-03 02:33 UTC, evinhaela approved these changes

2021-10-05 05:15 UTC, merged

2021-10-05 05:20 UTC, eldadfux commented
THANK YOU! All changes merged 🥳

Please reach out to `eldadfux` on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags!

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) to help make Appwrite better.