Feat add translation latin
appwrite/appwrite pull request #2015
Opened 2021-10-06 15:55 UTC by fernandoamz

## What does this PR do?
Add translation and files to load Spanish Lat.

## Test Plan
Someone who can run the project should make a checkout to review if the files and translations for latin are running correctly.

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

This PR add the feature from this issue.
https://github.com/appwrite/appwrite/issues/1746

2021-11-05 23:15 UTC, fernandoamz commented
I fixed the last comment @christyjacob4, thanks for your feedback

2021-11-17 08:41 UTC, christyjacob4 requested changes

2021-11-17 08:41 UTC, christyjacob4 commented on app/config/locale/codes.php
> +<<<<<<< HEAD
You have committed the code while resolving a merge conflict. Please fix this

2021-11-17 16:59 UTC, fernandoamz commented
Hi @christyjacob4 , I fixed the requested changes

2021-11-28 10:42 UTC, christyjacob4 commented on app/config/locale/codes.php
> +    'la', // Latin
```suggestion
```
We still have 2 occurrences for the Latin language. Can you remove this one. ?

2021-11-28 10:43 UTC, christyjacob4 requested changes
Please address one last comment. Rest looks good 👍

2021-11-29 14:17 UTC, fernandoamz commented
Thanks so much @christyjacob4, I fixed the last comment.

2021-11-29 15:30 UTC, christyjacob4 approved these changes

2021-11-29 15:30 UTC, merged

2021-11-29 15:30 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) and help make Appwrite better :)