fix function model permission
appwrite/appwrite pull request #2332
Opened 2021-10-22 10:34 UTC by lohanidamodar

## What does this PR do?

Fixes the response model for Function permission, previously it was using the permission but as function only has execute permission and not read-write so it was not working as expected

## Test Plan

N/A

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

YES

2021-11-16 22:46 UTC, kodumbeats approved these changes

2021-11-16 22:48 UTC, kodumbeats requested changes
After some more thinking, I don't think we should abbreviate `FuncPermissions` - can we use the entire words? (Could be wrong, but I don't think we use abbreviations a lot in the codebase)

2021-11-17 13:12 UTC, lohanidamodar commented
@kodumbeats as the original func model is abbreviated to func, this feels right doesn't it? Do we even update the original function model to Function instead?

2021-11-17 13:23 UTC, TorstenDittmann approved these changes

2021-11-18 05:19 UTC, eldadfux commented
After we flattened the permissions model for documents and files, shouldn't we do the same for function?

Maybe $execute? WDYT?

2021-11-18 05:27 UTC, lohanidamodar commented
> After we flattened the permissions model for documents and files, shouldn't we do the same for function?
> 
> Maybe $execute? WDYT?

Agreed, but this is for the current master, having issue on Dart SDK response models because of this.

2021-11-18 05:47 UTC, eldadfux commented
> > After we flattened the permissions model for documents and files, shouldn't we do the same for function?
> > Maybe $execute? WDYT?
> 
> Agreed, but this is for the current master, having issue on Dart SDK response models because of this.

OK, but let's make sure this is tackled in newer branches.

2021-11-18 05:47 UTC, merged