Feat-mock-upload-chunked
appwrite/appwrite pull request #2381
Opened 2021-11-02 05:34 UTC by lohanidamodar

## What does this PR do?

Chunked upload tests on mock API to test chunked upload support on SDKs

## Test Plan

N/A

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

YES

2021-11-02 09:14 UTC, TorstenDittmann approved these changes

2021-11-02 09:14 UTC, TorstenDittmann commented on app/controllers/mock.php
> +            var_dump($id);
leftover

2021-11-02 10:50 UTC, christyjacob4 commented on app/controllers/mock.php
>          $file = $request->getFiles('file');
Can we use a different name for this variable instead of `$file` because we're using the same variable for the request param in line 238

2021-11-02 10:53 UTC, christyjacob4 requested changes
Just one comment :)

2021-11-02 10:53 UTC, christyjacob4 commented on app/controllers/mock.php
>          $file = $request->getFiles('file');
Also why are we not using the `$file` variable from L238 ?

2021-11-03 04:42 UTC, lohanidamodar commented
@christyjacob4 can please check the Storage controller, we do similar thing there. We do this because the utopia framework doesn't yet provide a way to access actual file from `$file` parameter. so we override it.

2021-11-04 09:17 UTC, christyjacob4 approved these changes

2021-11-04 09:18 UTC, christyjacob4 commented
@lohanidamodar Thanks for clarifying 👍

2021-11-04 09:19 UTC, lohanidamodar commented
> @lohanidamodar Thanks for clarifying +1

No problem!

2021-11-04 09:19 UTC, merged