Overhauling the teams documentation
appwrite/appwrite pull request #2397
Opened 2021-11-06 13:33 UTC by rdmchr

## What does this PR do?

I'm rewriting the teams documentation to make it easier to understand and fix mistakes.

## Related PRs and Issues

#2359 

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
✔

2021-11-06 13:35 UTC, rdmchr commented
Current progress:

- [x] Create Team
- [x] List Teams
- [x] Get Team
- [x] Update Team
- [x] Delete Team
- [ ] Create Team Membership
- [ ] Update Membership Roles
- [ ] Get Team Memberships
- [ ] Update Team Membership Status
- [ ] Delete Team Membership

2021-12-02 21:35 UTC, kodumbeats requested changes
Apologies for the delay on the review! This is a good first polish :)

I've requested a few specific changes, but I'm seeing some inconsistency across different sections of the docs changes - could you take a second pass at your text while trying to make each endpoint's description match the style of the rest?

A few ideas to think about:
- Which endpoints should have an article to begin their sentences (a/an/the)?
- How does the tense of these docs match in comparison to others?

Let me know once you've had your go, and I'll review it promptly 🙈

2021-12-02 21:35 UTC, kodumbeats commented on docs/references/teams/get-team-members.md
> +Lists a teams members using the team's unique ID. All team members have read access to this endpoint.
```suggestion
Lists a team's members using the team's unique ID. All team members have read access to this endpoint.
```

2021-12-08 22:27 UTC, rdmchr commented
I think I fixed the inconsistencies and the tense also seem right.
Just one question, which do you prefer?

"_In admin mode, [...]_"
"_On admin mode, [...]_"
https://github.com/rdmchr/appwrite/blob/update-teams-doc/docs/references/teams/list-teams.md?plain=1#L3

I feel like the first one sounds better, but that might just be me.

2021-12-09 22:30 UTC, kodumbeats requested changes
We're super close! Thanks for all your hard work on these docs changes. I've got just a few more small things, then this PR is good to go 👍🏻 

1. I agree that adding articles at the beginning of these in-line docs is more readable, but I just realized it doesn't match the other docs. If we make this change here, we should make it everywhere - we can do that at a later time all at once, so for now, let's remove the articles.
2. In the markdown docs files, I think `Use this endpoint to` reads as a bit redundant since it's found in the endpoint docs 🤔 Let's remove this phrase as a prefix.

2021-12-10 17:20 UTC, kodumbeats requested changes

2021-12-10 17:20 UTC, kodumbeats commented on app/controllers/api/teams.php
> +    ->param('offset', 0, new Range(0, 2000), 'Use this value to manage pagination. The default value is 0.', true)
```suggestion
    ->param('offset', 0, new Range(0, 2000), 'Results offset. The default value is 0. Use this value to manage pagination.', true)
```

2021-12-10 17:20 UTC, kodumbeats commented on app/controllers/api/teams.php
>      ->param('offset', 0, new Range(0, 2000), 'Results offset. The default value is 0. Use this param to manage pagination.', true)
```suggestion
    ->param('offset', 0, new Range(0, 2000), 'Results offset. The default value is 0. Use this value to manage pagination.', true)
```

2021-12-10 17:23 UTC, kodumbeats requested changes

2021-12-10 17:24 UTC, kodumbeats approved these changes
Made a few small tweaks really quickly, and now it LGTM 👍🏻

2021-12-13 06:11 UTC, eldadfux commented
@kodumbeats, as part of 0.12, @TorstenDittmann has dropped the use of the term "Unique". The relevant diff: https://github.com/appwrite/appwrite/pull/2478/files - we should use consistent terms now.

2021-12-13 17:15 UTC, rdmchr commented
> @kodumbeats, as part of 0.12, @TorstenDittmann has dropped the use of the term "Unique". The relevant diff: https://github.com/appwrite/appwrite/pull/2478/files - we should use consistent terms now.

Should be fixed now.

2021-12-14 21:34 UTC, kodumbeats approved these changes

2021-12-16 05:55 UTC, eldadfux approved these changes

2021-12-16 05:56 UTC, eldadfux commented
Waiting for tests to pass.

2021-12-16 07:25 UTC, merged

2021-12-16 07:25 UTC, eldadfux commented
Merged! Thank you so much @rdmchr !!