Feat new spec formats
appwrite/appwrite pull request #2539
Opened 2022-01-01 02:33 UTC by eldadfux

## What does this PR do?

Instead if relying on an HTTP endpoint to generate our specs in realtime for our latest version, we can use the static files for showing specs for different supported versions.

This will help to solve the issue where some of the paths in the homepage are missing, and help reduce the dependencies between appwrite/appwrite and appwrite.io.
https://appwrite.io/specs/open-api3?platform=client
https://appwrite.io/specs/open-api3?platform=server
https://appwrite.io/specs/swagger2?platform=client
https://appwrite.io/specs/swagger2?platform=server

## Test Plan

Tests could be covered in the homepage.

## Related PRs and Issues

#2527

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2022-01-01 13:37 UTC, christyjacob4 commented on tests/e2e/General/HTTPTest.php
> +                        }
Leftovers I believe?

2022-01-01 13:37 UTC, christyjacob4 approved these changes

2022-01-01 13:56 UTC, TorstenDittmann requested changes

2022-01-01 13:56 UTC, TorstenDittmann commented on app/tasks/specs.php
> +        });
```suggestion
        App::setResource('request', fn() => new Request);
        App::setResource('response', fn() => $response);
```

we can be fancy here now :-)

2022-01-01 13:56 UTC, TorstenDittmann commented on src/Appwrite/Specification/Format/Swagger2.php
> +                            // $items['$ref'] = '#/definitions/document';
leftover comment

2022-01-01 13:56 UTC, TorstenDittmann commented on tests/e2e/General/HTTPTest.php
> +                        }
leftovers 👍🏻

2022-01-01 13:56 UTC, TorstenDittmann commented on app/tasks/specs.php
> +                        }, $modelLabel) : $response->getModel($modelLabel);
`$model` is never used 🤔

2022-01-01 13:56 UTC, TorstenDittmann commented on src/Appwrite/Specification/Format/OpenAPI3.php
> +                        foreach ($rule['type'] as $key => $value) {
```suggestion
                        foreach ($rule['type'] as $value) {
```

we never use the `$key` here

2022-01-01 13:56 UTC, TorstenDittmann commented on src/Appwrite/Specification/Format/Swagger2.php
> +                        foreach ($rule['type'] as $key => $value) {
```suggestion
                        foreach ($rule['type'] as $value) {
```

2022-01-01 13:56 UTC, TorstenDittmann commented on app/cli.php
> +require_once __DIR__.'/controllers/general.php';
This should be in `specs.php` since it adds like 2-4 seconds delay for every CLI command 👍🏻

2022-01-01 13:57 UTC, TorstenDittmann commented on app/cli.php
> +require_once __DIR__.'/controllers/general.php';
nvm, looks like my docker was just a bit funky and slow

2022-01-03 09:20 UTC, TorstenDittmann approved these changes

2022-01-03 09:28 UTC, merged