fix: check whether the membershipId has been confirmed to avoid recon…
appwrite/appwrite pull request #2594
Opened 2022-01-12 10:33 UTC by Malte2036

## What does this PR do?

The changes check when calling the "Update Team Membership Status" endpoint whether the membershipId parameter has already been confirmed to prevent the same membershipId from being confirmed more than once. 

If the membershipId has already been confirmed, an error is thrown and the process is aborted.

## Related PRs and Issues

Fix for this bug  #2593. :bug:

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

yes

2022-01-13 11:57 UTC, eldadfux requested changes
Good catch! Left a few suggestions.

2022-01-13 11:57 UTC, eldadfux commented on app/controllers/api/teams.php
> +            throw new Exception('Membership already confirmed', 400);
```suggestion
            throw new Exception('Membership already confirmed', 409);
```

I think 409 will be more descriptive here.

2022-01-13 11:57 UTC, eldadfux commented on app/controllers/api/teams.php
> +            throw new Exception('Membership already confirmed', 400);
Reference: https://appwrite.io/docs/error-codes

2022-01-13 11:57 UTC, eldadfux commented on app/controllers/api/teams.php
> +        if ($membership->getAttribute('confirm') !== false) {
```suggestion
        if ($membership->getAttribute('confirm') === true) {
```

Checking for acceptance feels a bit safer.

2022-01-13 17:25 UTC, eldadfux commented
Waiting for tests to pass, the docker rate limit seems to make problems.

2022-01-18 13:41 UTC, TorstenDittmann commented
Restarted the CI 👍🏻

2022-01-18 22:35 UTC, Malte2036 commented
Tests should be fixed and added new e2e-test :robot:

2022-01-19 09:27 UTC, Malte2036 commented
The `e2e/Services/Functions` tests fail even without my changes.
All `e2e/Services/Teams` tests work, so I think the pull request is ready to merge.

2022-01-30 23:07 UTC, eldadfux approved these changes

2022-01-30 23:08 UTC, eldadfux commented
@Malte2036 I think you need to sync with master in order for tests to pass.

2022-02-09 12:15 UTC, Malte2036 commented
Ready to merge @eldadfux? 🤔

2022-03-03 13:23 UTC, TorstenDittmann commented
Looks like we missed that one, will take care of this 👍🏻

2022-03-03 13:40 UTC, merged

2022-03-03 13:42 UTC, TorstenDittmann commented
Merged it and will be released soon! Thanks alot 🥳 

Sorry for the delay - the team was in release stress 🙇🏻