feat: Make OAuth2 Microsoft Provider configureable
appwrite/appwrite pull request #2624
Opened 2022-01-17 09:42 UTC by BobcatProgrammer

## What does this PR do?

This PR enables configuration of the TenantId for the Microsoft OAuth2 provider as documented [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols#endpoints). This enables control over what types of accounts can authenticate via Microsoft.

To facilitate this the PR also changes how custom OAuth2 providers can be configured. Details can be found in the [docs](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-oauth2-provider.md)

### Open Points in DRAFT

- [ ] Make the JS part generic
- [ ] Migrate Apple Provider to new structure
- [ ] Update [Docs](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-oauth2-provider.md)

## Test Plan

- [ ] Test Microsoft Provider with `common`
- [ ] Test Microsoft Provider with `organizations`
- [ ] Test Microsoft Provider with `consumers`
- [ ] Test Microsoft Provider with `{my tenant id}`
- [ ] Test Apple provider Form works with generic JS

## Related PRs and Issues

Fixes #926 
Prepares for #1668 

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

yes of course, even multiple times 😃

2022-01-17 12:57 UTC, eldadfux requested changes
Added a few small suggestions. Would be great to get a screenshot of the new form.

2022-01-17 12:57 UTC, eldadfux commented on app/views/console/users/index.phtml
> +                                            $form_view = new View(__DIR__.'/oauth/'.$this->escape($form));
```suggestion
                                            $form = new View(__DIR__.'/oauth/'.$this->escape($form));
```

We use camelCase and try to stick to shorter names when possible.

2022-01-17 12:57 UTC, eldadfux commented on app/views/console/users/index.phtml
> +                                            echo $form_view
```suggestion
                                            echo $form;
```

2022-01-17 12:57 UTC, eldadfux commented on app/views/console/users/index.phtml
> +                                                ->setParam("provider",$provider)
```suggestion
                                                ->setParam("provider", $provider)
```

2022-01-17 13:04 UTC, BobcatProgrammer commented
![image](https://user-images.githubusercontent.com/22432834/149774220-e7bf98a2-123c-4217-a7ea-7654c7642a0c.png)
Screenshot of Microsoft OAuth Provider Form

2022-01-24 21:49 UTC, eldadfux approved these changes

2022-01-26 06:26 UTC, eldadfux commented
Please try to sync with master, tests might be failing because of other build issues the core team had.

2022-01-26 08:15 UTC, BobcatProgrammer commented
> Please try to sync with master, tests might be failing because of other build issues the core team had.

done! can someone retrigger the checks please?

2022-01-26 09:55 UTC, christyjacob4 commented on src/Appwrite/Auth/OAuth2/Microsoft.php
> +    }
```suggestion
    protected function decodeJson():array
    {    
        try {
            $secret = \json_decode($this->appSecret, true);
        } catch (\Throwable $th) {
            throw new Exception('Invalid secret');
        }
        return $secret;
    }
```

2022-01-26 09:56 UTC, christyjacob4 commented on src/Appwrite/Auth/OAuth2/Microsoft.php
> +    protected function getTenantId():string
```suggestion
    protected function getTenantId(): string
```

2022-01-26 09:57 UTC, christyjacob4 commented on src/Appwrite/Auth/OAuth2/Microsoft.php
> +    protected function getClientSecret():string
```suggestion
    protected function getClientSecret(): string
```

2022-01-26 09:57 UTC, christyjacob4 requested changes
Amazing work on the PR! Just some minor PSR compliance and we're good to merge 👍

2022-01-30 18:27 UTC, eldadfux approved these changes

2022-01-30 19:55 UTC, merged

2022-01-30 19:55 UTC, eldadfux commented
Amazing work @BobcatProgrammer, thank you so much for making this contribution to the project!