Feat cleanup executor
appwrite/appwrite pull request #2704
Opened 2022-01-27 09:31 UTC by PineappleIOnic

## What does this PR do?

Cleanups up aspects of the executor to bring it more inline with appwrite itself

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
Yes, I have

2022-01-27 09:38 UTC, christyjacob4 approved these changes

2022-01-31 10:42 UTC, christyjacob4 commented on app/executor.php
> +            ->json(['success' => true]);
```suggestion
        return $response
            ->setStatusCode(Response::STATUS_CODE_OK)
            ->send();
```

2022-01-31 10:43 UTC, christyjacob4 commented on app/executor.php
> +                    ->json(['success' => true]);
```suggestion
                $response
                    ->setStatusCode(Response::STATUS_CODE_OK)
                    ->send();
```

2022-01-31 10:43 UTC, christyjacob4 commented on app/executor.php
> +                        ->json(['success' => true]);
```suggestion
                    $response
                        ->setStatusCode(Response::STATUS_CODE_OK)
                        ->send();
```

2022-01-31 10:44 UTC, christyjacob4 requested changes
Please address the comments

2022-01-31 10:49 UTC, christyjacob4 commented on app/executor.php
> +            $orchestration = $orchestrationPool->get();
Added it inside the `try`

2022-01-31 10:52 UTC, TorstenDittmann commented on app/executor.php
> +                if ($build->getAttribute('status') == 'building') {
Always to strict equal `===`

2022-01-31 11:01 UTC, merged