Feat: Improved SSL generation
appwrite/appwrite pull request #3034
Opened 2022-03-29 10:22 UTC by Meldiron

## What does this PR do?

- If APP_DOMAIN is set, only allow certificates for this domain
- If APP_DOMAIN is not set, allow the first one, and remember it's the main domain. This makes DO 1click frictionless
- Renamed 'master' domain to 'main' domain in logs

- Custom domains are not affected. SSL generation for these is triggered from Console (you click to trigger it 'Verify now')
- Renewing is not affected. Renewing is done with a schedule in Resque.

## Test Plan

- [x] Manual QA on DO:

![CleanShot 2022-03-29 at 12 16 45](https://user-images.githubusercontent.com/19310830/160590319-2c14259d-ae26-4980-874f-35aa3da43034.png)
![CleanShot 2022-03-29 at 12 16 42](https://user-images.githubusercontent.com/19310830/160590327-a323c3d5-249c-4dd8-95de-0d5c34375527.png)

## Related PRs and Issues

x

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2022-03-29 10:52 UTC, lohanidamodar approved these changes
Looks good to me. Let's just remember to update our docs regarding certificates about these changes, telling people to set the domain  env if they run into this issue and more.

2022-03-30 07:20 UTC, Meldiron commented on app/controllers/general.php
> +            if(!empty(App::getEnv('_APP_DOMAIN_TARGET', ''))) {
Domain target or app domain?

2022-04-04 08:15 UTC, Meldiron commented on app/controllers/general.php
> +            if(!empty(App::getEnv('_APP_DOMAIN_TARGET', ''))) {
Target seems to be used for CNAME validation. Renaming to app_domain.

2022-04-22 10:03 UTC, christyjacob4 commented on app/controllers/general.php
> +                    Resque::enqueue('v1-certificates', 'CertificatesV1', [
```suggestion
                    Resque::enqueue(Event::CERTIFICATES_QUEUE_NAME, Event:: CERTIFICATES_CLASS_NAME, [
```

2022-04-22 10:05 UTC, christyjacob4 commented on app/controllers/general.php
> +                    Resque::enqueue('v1-certificates', 'CertificatesV1', [
You will also need to import the Event class.
This file does not contain it.

2022-04-22 10:07 UTC, christyjacob4 requested changes
some minor changes

2022-04-26 09:19 UTC, christyjacob4 approved these changes

2022-04-26 11:07 UTC, merged