Create Auth0 OAuth Adapter
appwrite/appwrite pull request #3048
Opened 2022-04-01 11:12 UTC by adityaoberai

## What does this PR do?

Adds Auth0 OAuth Adapter

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

None

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2022-04-01 11:34 UTC, adityaoberai commented
Here are some snippets from the Users page

<img width="752" alt="image" src="https://user-images.githubusercontent.com/31401437/161255014-1d92b88d-ad93-461f-b2e2-5eeb3626f59a.png">

![Screenshot 2022-04-01 170143_censored](https://user-images.githubusercontent.com/31401437/161255620-c199d082-fd3e-4992-882a-739902350a4e.jpg)

2022-04-02 13:16 UTC, christyjacob4 commented on src/Appwrite/Auth/OAuth2/Auth0.php
> +     * @return string
Have a new line here

2022-04-02 13:16 UTC, christyjacob4 commented on src/Appwrite/Auth/OAuth2/Auth0.php
> +     * @return string
Have a new line here

2022-04-02 13:19 UTC, christyjacob4 commented on src/Appwrite/Auth/OAuth2/Auth0.php
> +    public function refreshTokens(string $refreshToken):array
```suggestion
    public function refreshTokens(string $refreshToken): array
```
PSR-12 style guides
<img width="1143" alt="Screenshot 2022-04-02 at 4 18 50 PM" src="https://user-images.githubusercontent.com/20852629/161385135-6ea771e7-81db-421a-a6a6-9cbfadf550ef.png">

2022-04-02 13:19 UTC, christyjacob4 commented on src/Appwrite/Auth/OAuth2/Auth0.php
> +    protected function getUser(string $accessToken)
```suggestion
    protected function getUser(string $accessToken): array
```

2022-04-02 13:20 UTC, christyjacob4 commented on src/Appwrite/Auth/OAuth2/Auth0.php
> +    protected function decodeJson(): array
```suggestion
    protected function getAppSecret(): array
```

2022-04-02 13:21 UTC, christyjacob4 commented on src/Appwrite/Auth/OAuth2/Auth0.php
> +            $secret = \json_decode($this->appSecret, true);
```suggestion
            $secret = \json_decode($this->appSecret, true, 512, JSON_THROW_ON_ERROR);
```

2022-04-02 13:21 UTC, christyjacob4 commented on src/Appwrite/Auth/OAuth2/Auth0.php
> +            throw new Exception('Invalid secret');
```suggestion
            throw new \Exception('Invalid secret');
```

2022-04-02 13:21 UTC, christyjacob4 commented on src/Appwrite/Auth/OAuth2/Auth0.php
> +            $secret = \json_decode($this->appSecret, true);
We need this flag, else json_decode wont throw any error.

2022-04-02 13:22 UTC, christyjacob4 commented on src/Appwrite/Auth/OAuth2/Auth0.php
> +     * @return array
Add a new b/w the description and the return doc

2022-04-02 13:22 UTC, christyjacob4 requested changes
Looks good 👍 
Some small changes.

2022-04-03 16:39 UTC, adityaoberai commented
@christyjacob4 I have added the suggested changes and manually tested the OAuth adapter.

2022-04-11 16:40 UTC, adityaoberai commented
> Awesome work 👏

Thank you 😁

2022-04-26 11:19 UTC, christyjacob4 commented
Waiting for tests....

2022-04-26 11:35 UTC, adityaoberai commented
I did some manual QA earlier for the adapter.
Got a valid response in the created session.

```
{
	"$id": "6267d83aa26050478d98",
	"userId": "6267d83a983fe7f791f8",
	"expire": 1682508730,
	"provider": "auth0",
	"providerUid": "auth0|6267d8324cac35006c77c20f",
	"providerAccessToken": "eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIiwiaXNzIjoiaHR0cHM6Ly9hcHB3cml0ZS10ZXN0LmpwLmF1dGgwLmNvbS8ifQ..DdfrLMBpIzxzRXmh.Xb8zlPnqzTGgiwmklessHhdE54tFtopLge6kA7Yj5EUKJpHljr7_f4hcLFtLtSG3kYGIc7JOtxwt5vDvkgEUAqAMrdQVCw9wDdTFP2eXRzAt4-Kydm4zC-AsYVn8BAdAuBNM45oBqNNjNWn1yt-5GgHKq2JgRxzzL5wtYdzftlihI4gJpUIjZdZWOHmn31P4nJOEdKgal-TpJeoYwDwv7A1hXZ4V8BkkWemkb9EdgG7qqnlWAiNYL8PRU9vFqNhMbnbQK4U4xPlkWOQj7k5u8ItSapl27Rtj7vN7xkiMtBc7gsw7V0LJq2q62CxVod-c3H56Fj7aVapwsx-REqjPo9eU7w.toAVB6xL4tRrjuwSzyWqEw",
	"providerAccessTokenExpiry": 1651059130,
	"providerRefreshToken": "v1.MZwxdaibdfbmvO_JqOMomMA1Gw34XoT9FF-AFTIylSak_rP4ogLjUF0RT_32qF7VDkLJ1QVuZ0j8bI_f5gfOwJ4",
	"ip": "172.21.0.1",
	"osCode": "WIN",
	"osName": "Windows",
	"osVersion": "10",
	"clientType": "browser",
	"clientCode": "CH",
	"clientName": "Chrome",
	"clientVersion": "100.0",
	"clientEngine": "Blink",
	"clientEngineVersion": "",
	"deviceName": "desktop",
	"deviceBrand": "",
	"deviceModel": "",
	"countryCode": "--",
	"countryName": "Unknown",
	"current": true
}
```

2022-04-26 13:28 UTC, christyjacob4 approved these changes

2022-04-26 13:29 UTC, merged