Fix: Failed indexes in queries
appwrite/appwrite pull request #3060
Opened 2022-04-05 16:48 UTC by Meldiron

## What does this PR do?

Currently, both `queries` and `orderAttributes` consider index allowed even if it has failed to be created.

With this PR, they will now both properly throw 'Index not found' if index wasn't successfully created.

## Test Plan

- [x] Manual QA on Gitpod (test both queries and orders)

With failed index:

![CleanShot 2022-04-05 at 18 39 34](https://user-images.githubusercontent.com/19310830/161805730-22d9d25a-286d-40a3-88c4-b6e6bd3d8cf0.png)
![CleanShot 2022-04-05 at 18 45 44](https://user-images.githubusercontent.com/19310830/161805738-3f563c14-fd36-4c43-aa64-c95a71af0760.png)

With available index:

![CleanShot 2022-04-05 at 18 38 56](https://user-images.githubusercontent.com/19310830/161805788-969006e1-3639-4acc-b9b7-d66eeb29565e.png)

![CleanShot 2022-04-05 at 18 45 53](https://user-images.githubusercontent.com/19310830/161805799-3f6ed2a7-57dc-4b82-a35b-2a3bf90f6565.png)

## Related PRs and Issues

x

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2022-04-10 07:09 UTC, eldadfux commented
My only question: should this be part of Appwrite or Utopia?

2022-04-11 07:09 UTC, Meldiron commented
> My only question: should this be part of Appwrite or Utopia?

I made this mistake 😅 It was part of Utopia PR previously: https://github.com/utopia-php/database/pull/118

Status of the attribute is Appwrite-specific, as worker-database if appwrite-specific. If you use Utopia directly, you don't need to wait for the attribute to get ready - your code gets blocked until it is.

With this reason, I decided to close Utopia PHP PR, and create one for Appwrite.

2022-04-17 11:57 UTC, TorstenDittmann approved these changes

2022-04-22 09:58 UTC, christyjacob4 commented on app/controllers/api/database.php
> +use Appwrite\Utopia\Database\Validator\OrderAttributes as OrderAttributesValudator;
```suggestion
use Appwrite\Utopia\Database\Validator\OrderAttributes as OrderAttributesValidator;
```

2022-04-22 09:59 UTC, christyjacob4 commented on app/controllers/api/database.php
> +            $validator = new OrderAttributesValudator($collection->getAttribute('attributes', []), $collection->getAttribute('indexes', []), true);
```suggestion
            $validator = new OrderAttributesValidator($collection->getAttribute('attributes', []), $collection->getAttribute('indexes', []), true);
```

2022-04-22 10:01 UTC, christyjacob4 requested changes
Looks good 👍 
Just a typo

2022-04-25 14:41 UTC, merged