Fix 'magic URL' accounts from not being able to create a new password.
appwrite/appwrite pull request #3092
Opened 2022-04-13 10:29 UTC by PineappleIOnic

## What does this PR do?

This PR fixes magic URL generated accounts from not being able to set a new password by setting the 'passwordUpdate' field on account creation to 0.

## Test Plan

A new test has been added to `AccountBase.php` which will attempt to update the password after creating a new account using magicURL.

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes, I have

2022-04-13 11:50 UTC, eldadfux requested changes
How did this behavior change? I'm pretty sure it was already doing that.
We should also update the updatePassword docs to reflect this behavior.

2022-04-13 15:57 UTC, eldadfux approved these changes

2022-04-14 14:07 UTC, eldadfux reviewed
Thinking about it, we should probably have a test for this. cc @TorstenDittmann

2022-04-17 11:54 UTC, TorstenDittmann approved these changes

2022-04-19 13:51 UTC, merged