Add authentik as a OAuth provider
appwrite/appwrite pull request #3180
Opened 2022-05-05 13:12 UTC by Aragur

## What does this PR do?

This PR adds [authentik](https://goauthentik.io/) as a authentification provider.  
This is a killer feature for me, as this is the only *self-hosted* OAuth provider.

## Test Plan

I tested signing in with this [OAuth-Tester](https://github.com/AmreshSinha/OAuth-Tester-Appwrite).  
Everything worked  as intended.

## Related PRs and Issues

None 😄 (If required I may create an Feature-Request for this)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes I did.

2022-05-11 08:13 UTC, Aragur commented
@eldadfux Is there something wrong with my PR or why does nobody review or comment it?

2022-05-31 11:08 UTC, eldadfux commented
The team is pretty busy, we'll review it ASAP before the release of the next Appwrite version.

2022-06-08 22:06 UTC, christyjacob4 commented on src/Appwrite/Auth/OAuth2/Authentik.php
> +        return (isset($secret['authentikDomain'])) ? $secret['authentikDomain'] : '';
```suggestion
        return $secret['authentikDomain'] ?? ''; 
```

2022-06-08 22:07 UTC, christyjacob4 commented on src/Appwrite/Auth/OAuth2/Authentik.php
> +     *
```suggestion
```

2022-06-08 22:11 UTC, christyjacob4 commented on src/Appwrite/Auth/OAuth2/Authentik.php
> +        return (isset($secret['clientSecret'])) ? $secret['clientSecret'] : '';
```suggestion
        return $secret['clientSecret'] ?? ''; 
```

2022-06-08 22:12 UTC, christyjacob4 requested changes
Looks awesome! Just some minor comments :)

2022-06-08 22:15 UTC, christyjacob4 commented
@Aragur please sync with master, the tests are failing due to a missing CNAME.

2022-06-13 10:22 UTC, christyjacob4 commented
@Aragur So close to merging 😉 
Please check for the code formatting issue raised by the Linter and then we're good to merge. 
Can you also share some screenshots of the Users->Settings screen with the Authentik provider added and a screenshot of a session created with the authentik provider ?

2022-06-13 19:31 UTC, Aragur commented
> @Aragur So close to merging 😉 Please check for the code formatting issue raised by the Linter and then we're good to merge. Can you also share some screenshots of the Users->Settings screen with the Authentik provider added and a screenshot of a session created with the authentik provider ?

Thanks for you reply.  
The linting task wasn't there once I originaly created my pull request :) But it should be fixed now.

Here are the requested screenshots:
Users->Settings:
<img width="946" alt="Screenshot 2022-06-13 at 21 24 52" src="https://user-images.githubusercontent.com/11004008/173429642-834e7033-6564-4d0f-aee9-51b22dbaab1f.png">
Users->Settings->authentik-Details-Screen
<img width="681" alt="Screenshot 2022-06-13 at 21 25 14" src="https://user-images.githubusercontent.com/11004008/173429646-5c838211-9df5-49c6-bc93-d18d02689e0a.png">
OAuth-Screen:
<img width="650" alt="Screenshot 2022-06-13 at 21 29 28" src="https://user-images.githubusercontent.com/11004008/173430125-c78c0ea1-8f61-4f34-9409-945df3adb65d.png">
OAuth-Session-Details by [OAuth-Tester-Appwrite](https://github.com/AmreshSinha/OAuth-Tester-Appwrite)
<img width="679" alt="Screenshot 2022-06-13 at 21 29 36" src="https://user-images.githubusercontent.com/11004008/173430241-ea0f9963-5bcc-4d8c-956f-dda6bca4baf1.png">

2022-06-26 11:40 UTC, Aragur commented
So I modified all required steps 13 days ago...  
I DON'T want to resolve those merge conflicts again which only exists because of the lack of your communication.  
How should an OpenSource project work if you take over 2 months to accept a PR...

2022-07-01 16:21 UTC, MoritzHeld commented
I would really appreciate if you guys could accept this PR. Would love to use that feature in a project of mine!

2022-07-06 09:36 UTC, Aragur commented
@christyjacob4 Merge is done. All checks ran successfully. What to do next?

2022-07-07 15:01 UTC, Aragur commented on app/config/providers.php
> +        'name' => 'authentik',
So this is the default name (written with a small a).
You can see it on the main page of the docs: https://goauthentik.io

But if it's required by your guidelines, I of course can change it.

2022-07-08 09:01 UTC, Aragur commented
> One last comment

I don't know if you saw my comment on your comment. So here it is again:

So this is the default name (written with a small a).
You can see it on the main page of the docs: https://goauthentik.io/

But if it's required by your guidelines, I of course can change it.

2022-08-05 06:50 UTC, christyjacob4 commented
@Aragur  Sorry for the delay. Yes, our guidelines require the OAuth Provider names to be in title case so as to look consistent with the other providers in the UI

2022-08-05 06:53 UTC, Aragur commented
> @Aragur Sorry for the delay. Yes, our guidelines require the OAuth Provider names to be in title case so as to look consistent with the other providers in the UI

Okay, It's done now

2022-08-05 07:35 UTC, christyjacob4 approved these changes
Looks amazing! 🥳  Thank you for your help and patience!

2022-08-05 07:36 UTC, merged

2023-01-30 22:49 UTC, lost-RD commented
@Aragur please can you share your version of the OAuth-Tester-Appwrite repo? I'm struggling to get the auth flow right.

2023-02-02 19:02 UTC, Aragur commented
@lost-RD here you go: https://github.com/AmreshSinha/OAuth-Tester-Appwrite