Fix check oauth email verification
appwrite/appwrite pull request #3187
Opened 2022-05-07 12:11 UTC by christyjacob4

## What does this PR do?

* In case of OAuth providers that not guarantee a verified email, we should not merge them with an existing account session with the same email 
* Remove VK OAuth provider since they no longer expose the email  

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2022-05-07 16:36 UTC, eldadfux commented on app/controllers/api/account.php
> +                $user = $dbForProject->findOne('users', [new Query('deleted', Query::TYPE_EQUAL, [false]), new Query('email', Query::TYPE_EQUAL, [$email])]); // Get user by email address
We might want a new index

2022-05-08 16:16 UTC, TorstenDittmann commented on app/controllers/api/account.php
> +                $user = $dbForProject->findOne('users', [new Query('deleted', Query::TYPE_EQUAL, [false]), new Query('email', Query::TYPE_EQUAL, [$email])]); // Get user by email address
We already have an index for this 👍🏻

2022-05-08 16:22 UTC, TorstenDittmann requested changes
lgtm, but we can improve some code quality by removing all the `isset` calls.

2022-05-08 16:22 UTC, TorstenDittmann commented on src/Appwrite/Auth/OAuth2/Apple.php
> +        if (isset($this->claims['email_verified']) && $this->claims['email_verified'] === 'true') {
```suggestion
        if (($this->claims['email_verified'] ?? false) === 'true') {
```

2022-05-08 16:22 UTC, TorstenDittmann commented on src/Appwrite/Auth/OAuth2/Gitlab.php
> +        if (isset($user['confirmed_at']) && $user['confirmed_at'] !== null) {
```suggestion
        if ($user['confirmed_at'] ?? false) {
```

2022-05-08 16:22 UTC, TorstenDittmann commented on src/Appwrite/Auth/OAuth2/Google.php
> +        if (isset($user['email_verified']) && $user['email_verified'] === true) {
```suggestion
        if ($user['email_verified'] ?? false) {
```

2022-05-12 16:26 UTC, merged