Refactor `api.php`
appwrite/appwrite pull request #3290
Opened 2022-05-26 14:50 UTC by everly-gif

## What does this PR do?

Refactors `api.php`

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2022-05-27 09:45 UTC, christyjacob4 commented on app/controllers/shared/api.php
> +App::init(function (App $utopia, Request $request, Response $response, Document $project, Document $user, Event $events, Audit $audits, Mail $mails, Stats $usage, Delete $deletes, Event $database, Da
```suggestion
App::init(function (App $utopia, Request $request, Response $response, Document $project, Document $user, Event $events, Audit $audits, Mail $mails, Stats $usage, Delete $deletes, Event $database, Database $dbForProject, string $mode) {
```

2022-05-27 09:48 UTC, christyjacob4 commented on app/controllers/shared/api.php
> +App::init(function (App $utopia, Request $request, Response $response, Document $project, Document $user, Event $events, Audit $audits, Mail $mails, Stats $usage, Delete $deletes, Event $database, Da
Mode is a string as seen here
https://github.com/appwrite/appwrite/blob/master/app/init.php#L71-L72

2022-05-27 09:49 UTC, christyjacob4 commented on app/controllers/shared/api.php
> +App::shutdown(function (App $utopia, Request $request, Response $response, Document $project, Event $events, Audit $audits, Stats $usage, Delete $deletes, Event $database, bool $mode, Database $dbFor
```suggestion
App::shutdown(function (App $utopia, Request $request, Response $response, Document $project, Event $events, Audit $audits, Stats $usage, Delete $deletes, Event $database, string $mode, Database $dbForProject) {
```

2022-05-27 09:50 UTC, christyjacob4 requested changes
Please address the comments

2022-05-31 09:04 UTC, TorstenDittmann approved these changes

2022-05-31 09:04 UTC, merged