Allows to update permissions without payload
appwrite/appwrite pull request #3346
Opened 2022-06-06 22:55 UTC by gepd

## What does this PR do?

Currently, to update the permission of a document, you also have to update some kind of data, or at least pass some kind of data.

This does not work:

```js
await database.updateDocument(listCollection, list, {}, [`user:${user.$id}`]);
```

So to update permissions we have to pass some data, even if the data is the same as the current one:

```js
await database.updateDocument(listCollection, list, {name: "test"}, [`user:${user.$id}`]);
```

This change will allow to send an empty payload, but empty payload and read/write permission will keep throwing an error

```js
await database.updateDocument(listCollection, list, {}, [], []);
```

## Test Plan

No new test

## Related PRs and Issues

https://github.com/appwrite/appwrite/issues/2850

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

yes

2022-06-06 23:24 UTC, gepd commented
The failing test doesn't seems to be related with my changes

2022-06-07 17:10 UTC, TorstenDittmann commented
Restarted the tests 👍🏻 

I think it would make sense to make the `data` param optional. Otherwise it would be required but optional 🙂

2022-06-08 01:10 UTC, gepd commented
@TorstenDittmann good catch I totally forgot about that, I'm not good at types in PHP, but reading the manual, that should be the way to make it optional

let me know if that is enough 😀

2022-06-08 06:44 UTC, TorstenDittmann commented
Utopia has all those `->param` before the callback. If the last argument is true, the parameter of the rest API is marked as optional 😉

2022-06-09 00:54 UTC, gepd commented
@TorstenDittmann I think I got it, Is everyting good now?

2022-06-09 06:35 UTC, everly-gif commented on app/controllers/api/database.php
> +    ->action(function (string $collectionId, string $documentId, string|array|null $data, ?array $read, ?array $write, Response $response, Database $dbForProject, EventAudit $audits, Stats $usage, Ev
```suggestion
    ->action(function (string $collectionId, string $documentId, string|array $data, ?array $read, ?array $write, Response $response, Database $dbForProject, EventAudit $audits, Stats $usage, Event $events, string $mode) {
```
you can remove `null` from the types here , now that you have set the the last argument to true for the param.

2022-06-20 07:34 UTC, Meldiron requested changes

2022-06-20 20:30 UTC, gepd commented
@Meldiron can you reset the tests?

2022-06-21 04:12 UTC, gepd commented
I need help
After checking the test I realized there is something else looking for the document structure

I'm getting error `400` which I believe comes from here: https://github.com/gepd/appwrite/blob/feat-empty-payload/app/controllers/api/database.php#L1943

I'm not sure but, is this related to utopia php?

Seems like here is looking for a specific structure: https://github.com/utopia-php/database/blob/main/src/Database/Database.php#L1169-L1173

@Meldiron @TorstenDittmann

2022-06-22 07:50 UTC, Meldiron commented on app/controllers/api/database.php
> +        if (empty($data) && empty($read) && empty($write)) {
I am unsure about the `empty` check here. Would this allow me to set permissions to an empty array - remove all current permissions?

If not, we might need check with `isset` or `=== null` or `=== ''` or change default value when defining `->param()` to something else. Not sure, please play around to see what works the best.

2022-06-23 01:05 UTC, gepd commented
I have finally fixed, I have updated the test, I think not deleting the collection was causing problems

@Meldiron @TorstenDittmann

2022-06-24 12:07 UTC, Meldiron approved these changes
Looks good to me

2022-06-24 12:08 UTC, TorstenDittmann approved these changes

2022-06-24 12:09 UTC, merged