Adds Etsy to OAuth providers
appwrite/appwrite pull request #3522
Opened 2022-07-08 14:44 UTC by wess

## What does this PR do?

Adds Etsy as an OAuth Provider

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

Add application and enable in [Etsy](https://developer.etsy.com)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2022-07-11 10:17 UTC, TorstenDittmann commented
@wess linter is failing 👍🏻

2022-07-11 10:17 UTC, TorstenDittmann commented on .phpunit.result.cache
> +{"version":1,"defects":{"Appwrite\\Tests\\ComposeTest::testVersion":4,"Appwrite\\Tests\\ComposeTest::testServices":4,"Appwrite\\Tests\\ComposeTest::testNetworks":4,"Appwrite\\Tests\\ComposeTest::test
Can we remove that file and add it to `.gitignore`?

2022-07-14 15:28 UTC, TorstenDittmann commented on src/Appwrite/Auth/OAuth2/etsy.php
> +class Notion extends OAuth2
```suggestion
class Etsy extends OAuth2
```

2022-07-17 05:53 UTC, eldadfux commented on src/Appwrite/Auth/OAuth2/etsy.php
> +
@wess we need to remove this file.

2022-07-21 13:27 UTC, TorstenDittmann commented on src/Appwrite/Auth/OAuth2/Etsy.php
> +    private $endpoint = 'https://api.etsy.com/v3/public';
We have to add typings here and everywhere else 👍🏻 
```suggestion
    private string $endpoint = 'https://api.etsy.com/v3/public';
```

2022-07-21 13:27 UTC, TorstenDittmann commented on src/Appwrite/Auth/OAuth2/Etsy.php
> +        "transactions_w",
are all of those necessary to work?

Here should only be the bare minimum for it to work 👍🏻

2022-07-21 13:27 UTC, TorstenDittmann commented on src/Appwrite/Auth/OAuth2/Etsy.php
> +     * If present, the email is verified. This was verfied through a manual Stripe sign up process
This comment is wrong.

2022-07-21 13:27 UTC, TorstenDittmann commented on src/Appwrite/Auth/OAuth2/Etsy.php
> +     * If present, the email is verified. This was verfied through a manual Stripe sign up process
Can we double check that this is the case here as well?

2022-08-05 07:11 UTC, christyjacob4 approved these changes

2022-08-05 07:12 UTC, christyjacob4 commented on src/Appwrite/Auth/OAuth2/Etsy.php
> +    protected function getUser(string $accessToken)
```suggestion
    protected function getUser(string $accessToken): array
```

2022-08-05 07:13 UTC, christyjacob4 commented on src/Appwrite/Auth/OAuth2/Etsy.php
> +    private $version = '2022-07-14';
```suggestion
    private string $version = '2022-07-14';
```
As @TorstenDittmann  suggested, can you please add typings to all the variables ?

2022-08-05 07:14 UTC, christyjacob4 commented on src/Appwrite/Auth/OAuth2/Etsy.php
> +    private $pkce = '';
```suggestion
    /**
     * @var string
     */
    private string $pkce = '';
```

2022-08-05 07:14 UTC, christyjacob4 commented on src/Appwrite/Auth/OAuth2/Etsy.php
> +    private function getPKCE()
```suggestion
    private function getPKCE(): string
```

2022-08-05 07:15 UTC, christyjacob4 requested changes
Please address the comments

2022-08-09 13:38 UTC, christyjacob4 commented on app/config/providers.php
> +    'Etsy' => [
```suggestion
    'etsy' => [
```

The Keys for the providers are expected to be lower cased 👀

2022-08-09 13:39 UTC, christyjacob4 commented on src/Appwrite/Auth/OAuth2/Etsy.php
> +    protected $user = [];
```suggestion
    protected array $user = [];
```

2022-08-09 13:39 UTC, christyjacob4 commented on src/Appwrite/Auth/OAuth2/Etsy.php
> +    protected $tokens = [];
```suggestion
    protected array $tokens = [];
```

2022-08-09 13:40 UTC, christyjacob4 commented on src/Appwrite/Auth/OAuth2/Etsy.php
> +    private function getPKCE(): string
```suggestion
    /**
     * @return string
     */
    private function getPKCE(): string
```

2022-08-09 13:44 UTC, christyjacob4 requested changes
Looks good. Just a few more comments

2022-08-13 10:05 UTC, merged