docs: add one-click setups to README
appwrite/appwrite pull request #3559
Opened 2022-07-18 18:49 UTC by brandonroberts

## What does this PR do?

Adds existing one-click setups to README after primary install instructions

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2022-07-18 19:04 UTC, stnguyen90 requested changes

2022-07-18 19:04 UTC, stnguyen90 commented on README.md
> +        <img width="50" height="39" src="public/images/integrations/gitpod-logo.svg" alt="DigitalOcean Logo" />
```suggestion
        <img width="50" height="39" src="public/images/integrations/gitpod-logo.svg" alt="Gitpod Logo" />
```

2022-07-18 19:18 UTC, brandonroberts commented on README.md
> +        <img width="50" height="39" src="public/images/integrations/gitpod-logo.svg" alt="DigitalOcean Logo" />
Fixed

2022-07-19 04:00 UTC, eldadfux approved these changes

2022-07-19 04:00 UTC, merged

2022-07-19 04:00 UTC, eldadfux commented
Nice! Thanks @brandonroberts!