Feat response and request filters 0.16.x
appwrite/appwrite pull request #3697
Opened 2022-08-17 15:00 UTC by PineappleIOnic

## What does this PR do?

This PR implements the required response and request filters for 0.16.x to allow for backwards compatibility with prior SDK's

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
Yes

2022-09-09 15:23 UTC, TorstenDittmann commented on tests/unit/Utopia/Request/Filters/V15Test.php
> +        $this->assertEquals($expected, $result, 'fail');
is the 'fail' a leftover?

2022-09-09 17:56 UTC, stnguyen90 commented on tests/unit/Utopia/Request/Filters/V15Test.php
> +        $this->assertEquals($expected, $result, 'fail');
Yes 😅 . fixed

2022-09-10 01:01 UTC, stnguyen90 commented
What's left to do:

1. User
2. Variable
3. Webhooks
4. Probably additional usage responses
5. Various List models

2022-09-10 01:10 UTC, stnguyen90 commented
FYI, we'll need to handle time > duration after [this](https://github.com/appwrite/appwrite/pull/3805/commits/cb50220b6026445a6d1f6afd065b13cb97ae619d) is merged.

2022-09-13 00:14 UTC, stnguyen90 commented
> What's left to do:
> 
> 1. User
> 2. Variable
> 3. Webhooks
> 4. Probably additional usage responses
> 5. Various List models

Finished these. Should be ready.

2022-09-13 00:15 UTC, stnguyen90 approved these changes

2022-09-13 14:23 UTC, PineappleIOnic reviewed
lgtm

2022-09-13 19:37 UTC, christyjacob4 commented on app/controllers/general.php
> +                case version_compare($responseFormat, '0.15.0', '<='):
```suggestion
                case version_compare($responseFormat, '0.15.3', '<='):
```

2022-09-13 19:37 UTC, christyjacob4 commented on app/controllers/general.php
> +                case version_compare($responseFormat, '0.15.0', '<='):
Always use the highest patch version number 👍

2022-09-13 19:56 UTC, christyjacob4 commented on src/Appwrite/Utopia/Response/Filters/V15.php
> +        return $content;
we changed the `status` attribute which would previously be "enabled" or "disabled" to a boolean attribute  `enabled` which can be true or false 
https://github.com/appwrite/appwrite/pull/3798

2022-09-13 19:56 UTC, christyjacob4 commented on src/Appwrite/Utopia/Response/Filters/V15.php
> +        return $content;
The `time` attribute has been renamed to `duration`
https://github.com/appwrite/appwrite/pull/3801

2022-09-13 20:07 UTC, christyjacob4 commented on app/controllers/general.php
> +                case version_compare($requestFormat, '0.15.0', '<'):
```suggestion
                case version_compare($requestFormat, '0.15.3', '<'):
```

2022-09-13 20:40 UTC, christyjacob4 requested changes
Please address the comments

2022-09-13 22:28 UTC, christyjacob4 approved these changes
Looks good from me 👌

2022-09-13 22:52 UTC, merged