__stream
appwrite/appwrite pull request #3710
Opened 2022-08-22 16:07 UTC by shimonewman

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2022-08-23 09:56 UTC, eldadfux requested changes
Initial review. I still need to go more in detail through all the models, transcoding worker and controller.

Some general notes:
- We miss video update, list and get endpoints.
- The endpoint should always be prefixes with `videos` and not `video`.
- The video CRUD endpoints need to be first ones on the controllers.
- I see no reason for the `App::get('/v1/videos/buckets/:bucketId')` endpoint. It feels it duplicates the one we have in storage. In the future the storage list will have advanced filters that could allow us to fetch anything we want.

2022-08-23 13:09 UTC, shimonewman commented on app/config/videos-profiles.php
> +        'name' => '576p',
just for tests

2022-08-23 13:10 UTC, shimonewman commented on app/init.php
> +ini_set('memory_limit', '1024M');
debug left over, fixed

2022-08-23 13:18 UTC, shimonewman commented on src/Appwrite/Utopia/Response/Model/VideoRendition.php
> +class VideoRendition extends Model
ok

2022-08-23 13:28 UTC, shimonewman commented on src/Appwrite/Utopia/Response/Model/videoProfile.php
> +class VideoProfile extends Model
ok

2026-03-06 01:04 UTC, Hardanish-Singh approved these changes

2026-04-29 04:38 UTC, closed without merging