fix : Linode file upload failure
appwrite/appwrite pull request #3732
Opened 2022-08-29 16:00 UTC by everly-gif

## What does this PR do?

Fixes Linode File upload. It initially was failing because of the extra `/` in the request url.
It was making a request to a URL as below, which is invalid because of the consecutive `//`
```
https://<bucket-name>.eu-central-1.linodeobjects.com**//**storage/uploads/app-630cd8d7a106aa302d27/630cd8e90d3b33e8ff5c/6/3/0/c/630cdc2875416374d993.jpg
```
and hence failing.

Now, we trim the path string before uploading to remove the leading extra slash for providers such as Backblaze, Linode and Wasabi as they all require the removal.

## Test Plan

- [x] Manual   <br><br>
![](https://user-images.githubusercontent.com/77877486/187242868-7fa806fd-bb70-4cd2-bb81-51795d001d0f.jpeg)

## Related PRs and Issues

 #3433 

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2022-08-29 18:33 UTC, eldadfux requested changes
I feel like there's must be a more strategic place to have this check. @lohanidamodar @christyjacob4 any ideas?

2022-09-08 06:19 UTC, lohanidamodar commented
@eldadfux may be we can do the trim in the device constructor?
https://github.com/utopia-php/storage/blob/59802cf281d1976560cf6e353f250a9b870efddc/src/Storage/Device/S3.php#L115 ?

2022-09-08 07:37 UTC, eldadfux commented
Yeh, I think that can work. cc @everly-gif

2022-09-09 04:42 UTC, everly-gif commented
> Yeh, I think that can work. cc @everly-gif

sure , Ill make the changes there

2022-10-18 16:50 UTC, everly-gif commented
Closing this PR in favour of [#54](https://github.com/utopia-php/storage/pull/54/).

2022-10-18 16:50 UTC, closed without merging