Fix code examples in SDK getting started
appwrite/appwrite pull request #3777
Opened 2022-09-07 02:12 UTC by lohanidamodar

## What does this PR do?

- Fix stale code examples in SDK getting started files

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

YES

2022-09-07 05:14 UTC, abnegate requested changes

2022-09-07 05:14 UTC, abnegate commented on docs/sdks/android/GETTING_STARTED.md
>      Log.e("AppwriteException",e.message.toString())
```suggestion
    e.printStackTrace()
```

2022-09-07 05:14 UTC, abnegate commented on docs/sdks/android/GETTING_STARTED.md
> +    Log.d("Appwrite user", account.toMap())
```suggestion
    Log.d("Appwrite user", user.toMap())
```

2022-09-07 05:14 UTC, abnegate commented on docs/sdks/apple/GETTING_STARTED.md
> +    let account = try await account.create(
Just realised this will collide with the service variable

```suggestion
    let user = try await account.create(
```

2022-09-07 05:14 UTC, abnegate commented on docs/sdks/apple/GETTING_STARTED.md
> +    print(String(describing: account.toMap()))
```suggestion
    print(String(describing: user.toMap()))
```

2022-09-07 05:14 UTC, abnegate commented on docs/sdks/apple/GETTING_STARTED.md
> +        let account = try await account.create(
```suggestion
        let user = try await account.create(
```

2022-09-07 05:14 UTC, abnegate commented on docs/sdks/apple/GETTING_STARTED.md
> +        print(String(describing: account.toMap()))
```suggestion
        print(String(describing: user.toMap()))
```

2022-09-07 05:14 UTC, abnegate commented on docs/sdks/apple/GETTING_STARTED.md
> +        let account = try await account.get()
```suggestion
        let user = try await account.get()
```

2022-09-07 05:14 UTC, abnegate commented on docs/sdks/apple/GETTING_STARTED.md
> +        print(String(describing: account.toMap()))
```suggestion
        print(String(describing: user.toMap()))
```

2022-09-07 05:14 UTC, abnegate commented on docs/sdks/dotnet/GETTING_STARTED.md
> +    var user = await users.create(ID.unique(), 'email@example.com', 'password', 'name');
```suggestion
    var user = await users.Create(ID.Unique(), 'email@example.com', 'password', 'name');
```

2022-09-07 05:14 UTC, abnegate commented on docs/sdks/dotnet/GETTING_STARTED.md
> +  var user = await users.create(ID.unique(), 'email@example.com', 'password', 'name');
```suggestion
  var user = await users.Create(ID.Unique(), 'email@example.com', 'password', 'name');
```

2022-09-07 05:14 UTC, abnegate commented on docs/sdks/python/GETTING_STARTED.md
> +from appwrite.client import ID
```suggestion
from appwrite.id import ID
```

2022-09-07 05:14 UTC, abnegate commented on docs/sdks/kotlin/GETTING_STARTED.md
>          println(e)
```suggestion
        e.printStackTrace()
```

2022-09-07 05:22 UTC, abnegate approved these changes

2022-09-13 21:21 UTC, christyjacob4 approved these changes

2022-09-13 21:23 UTC, merged