Updated the sdk example for flutter
appwrite/appwrite pull request #3831
Opened 2022-09-14 11:16 UTC by Dynamite-fp

Updated `createSession` to `createEmailSession` as it was a bit confusing because `createSession` isn't defined.

2022-09-14 17:49 UTC, stnguyen90 requested changes

2022-09-14 17:49 UTC, stnguyen90 commented on docs/sdks/flutter/EXAMPLES.md
> +Response session = await account.createEmailSession(email: 'me@appwrite.io', password: 'password'); //Create Email And Password Session
To remain consistent with the previous code example and avoid a comment for self-explanatory code, let's remove the comment.

2022-09-14 18:03 UTC, christyjacob4 approved these changes

2022-09-16 16:15 UTC, stnguyen90 commented
@DynamiteFP, sorry, but it seems like this was already handled in https://github.com/appwrite/appwrite/pull/3841.

2022-09-16 21:58 UTC, closed without merging