Fixed typo in CONTRIBUTING.md
appwrite/appwrite pull request #3870
Opened 2022-09-17 15:27 UTC by toir427

Fixed typo in CONTRIBUTING.md

- `want contributing` -> `want to contribute`
- `there` -> `then`
- `wont` -> `won't`

2022-09-17 15:27 UTC, toir427 commented
`spcific` -> `specific`

2022-09-17 15:31 UTC, toir427 commented
I think you must use Appwrite not the Appwrite [info](https://www.google.com/search?q=can+i+use+the+article+before+organization+name&oq=can+i+use+the+article+before+organization+name&aqs=chrome..69i57j69i64.11361j1j7&sourceid=chrome&ie=UTF-8)

2022-10-05 23:33 UTC, stnguyen90 requested changes
@toir427 Great PR! 🤯 We left some comments during the review, please check them out.

2022-10-05 23:33 UTC, stnguyen90 commented on CONTRIBUTING.md
> +We would ❤️ for you to contribute to Appwrite and help make it better! We want to contribute to Appwrite to be fun, enjoyable, and educational for anyone and everyone. All contributions are welcome,
This was correct as is.

2022-10-05 23:33 UTC, stnguyen90 commented on CONTRIBUTING.md
> +1. `git pull`, before creating a new branch, pull the changes from upstream. Your master needs to be up-to-date.
This was correct as is. See: https://writingexplained.org/up-to-date-hyphenated

2024-02-18 22:40 UTC, stnguyen90 commented
Closing stale PR.

2024-02-18 22:40 UTC, closed without merging