fix: empty payload returned as list
appwrite/appwrite pull request #4050
Opened 2022-10-02 10:31 UTC by geisterfurz007

## What does this PR do?

This PR is an attempt at fixing #3916 showing an issue with empty payloads being returned as empty array instead of an empty object. The proposed fix is to check for the length of the payload and manually force serialization of it as an empty object since `json_encode` will interpret an empty array as empty list instead of empty object.

## Test Plan

I have to admit that I didn't build a full recreation of the issue and there is none included in the referenced issue soooo I took a shortcut (if you require me to build up a full reproduction I can do so though!) which I shall explain:

The Dart types in the referenced issue indicate that a realtime message's payload is always expected to be an object and never an array, so hooking into the place where the payload is serialized and ensuring empty payloads are serialized to an object (see [this SO answer](https://stackoverflow.com/a/8595884/6707985)) should do the trick.

A [small PHP Sandbox online](https://onlinephp.io/c/7ed4f) demonstrates the improved serialization for empty payload arrays.

## Related PRs and Issues

#3916 

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes.

2022-10-05 23:26 UTC, stnguyen90 requested changes
@geisterfurz007 Would you be able to either include a test case or a screenshot of before and after in the PR description?

2022-10-06 19:22 UTC, stnguyen90 commented
@geisterfurz007, a test case would be an e2e test. I don't think you need to mock redis because our e2e tests run the full Appwrite stack

2022-10-06 20:22 UTC, geisterfurz007 commented
Oh perfect, I will see what I can do then, thanks!

2022-10-25 16:06 UTC, geisterfurz007 commented
I fiddled around with this for a while but I am not really sure what to do with this, to be honest. With the scenario described in the linked issue, I could not replicate the issue in the tests (there was an assertion for a non-empty payload in there even!) and I made an ugly attempt to manually send an empty payload but the receive call times out:

```php
    public function testPayloadFormatOnDisconnect(): void
    {
        $client = $this->getWebsocket(['accounts']);
        $response = $client->receive();
        Realtime::send($this->getProject()['$id'], array(), array(), ['accounts'], ['role']);

        $response = $client->receive();

        $this->assertEquals('baked beans', $response);
    }
```

I would appreciate some guidance here; as said, I don't daily drive PHP and I have been struggling with this for some time now 😕

2022-10-25 17:26 UTC, stnguyen90 commented
> I would appreciate some guidance here; as said, I don't daily drive PHP and I have been struggling with this for some time now 😕

@geisterfurz007, [here's](https://github.com/appwrite/appwrite/blob/master/tests/e2e/Services/Realtime/RealtimeConsoleClientTest.php#L378-L426) a test where:

1. subscription is started:

https://github.com/appwrite/appwrite/blob/4942ba99518acdf6a51f99674e548b0932408c85/tests/e2e/Services/Realtime/RealtimeConsoleClientTest.php#L384-L397

2. API call is made to delete an attribute:

https://github.com/appwrite/appwrite/blob/4942ba99518acdf6a51f99674e548b0932408c85/tests/e2e/Services/Realtime/RealtimeConsoleClientTest.php#L402-L408

3. The realtime event is verified:

https://github.com/appwrite/appwrite/blob/4942ba99518acdf6a51f99674e548b0932408c85/tests/e2e/Services/Realtime/RealtimeConsoleClientTest.php#L409-L426

Maybe you can use this for guidance.

2022-10-25 18:11 UTC, geisterfurz007 commented
Right @stnguyen90, and there is one testcase that runs what I understood to be the problematic call in #3916:

https://github.com/appwrite/appwrite/blob/4942ba99518acdf6a51f99674e548b0932408c85/tests/e2e/Services/Realtime/RealtimeCustomClientTest.php#L501-L528

However in that testcase, there is an explicit assertion against an empty (deserialized) payload and indeed I could not reproduce an empty payload which is why I attempted to manually send an empty payload since I could not find any action that sends out an empty payload.

2022-10-25 21:00 UTC, stnguyen90 commented
@geisterfurz007, ah....looks like the problem happens specifically if 1 session is deleted from the Console.

2022-10-25 21:16 UTC, geisterfurz007 commented
@stnguyen90 How about this approach then to make this tested in a bit more isolation (before I go about and more or less randomly throw PHP around):

I move the json encoding of the payload / realtime JSON body to its own function and unit test that.

It might not be a test for the full problem case specifically in the issue but should still cover what ended up crashing the JSON parser in flutter (returning an empty list instead of an empty object).

2022-10-26 15:39 UTC, stnguyen90 commented
> How about this approach then to make this tested in a bit more isolation (before I go about and more or less randomly throw PHP around)

So, I may have gone down the wrong rabbit hole on this problem. Apologies for that. The payload should be the deleted session. We do it for `account.deleteSession()`:

https://github.com/appwrite/appwrite/blob/73bce1d7d025536ba70bcddca79566d2a679d440/app/controllers/api/account.php#L1823-L1827

but the problem is it's missing from the Users API:

https://github.com/appwrite/appwrite/blob/73bce1d7d025536ba70bcddca79566d2a679d440/app/controllers/api/users.php#L1005-L1007

Maybe you can add a test like 

https://github.com/appwrite/appwrite/blob/4942ba99518acdf6a51f99674e548b0932408c85/tests/e2e/Services/Realtime/RealtimeCustomClientTest.php#L501-L528

but use the [delete user session API](https://appwrite.io/docs/server/users?sdk=nodejs-default#usersDeleteSession) with something like:

https://github.com/appwrite/appwrite/blob/4942ba99518acdf6a51f99674e548b0932408c85/tests/e2e/Services/Realtime/RealtimeCustomClientTest.php#L1323-L1328

2022-10-26 16:31 UTC, geisterfurz007 commented
@stnguyen90 I'm super sorry but I am getting more and more confused 😅 The API you linked appears to be the one used in the test I referred to (targeting `'/account/sessions/' . $sessionNewId` as endpoint). The error also does not seem to be reproducible with a DELETE request to `/account/sessions` either.

2022-10-26 17:15 UTC, stnguyen90 commented
>  I'm super sorry but I am getting more and more confused

So sorry! Yes, the Delete Account Session test is working as expected. I was suggesting creating a new test that would delete a session using the Users API like:

```php
 $response = $this->client->call(Client::METHOD_DELETE, '/users/' . $userId . '/sessions' . $sessionId, [ 
     'content-type' => 'application/json', 
     'x-appwrite-project' => $this->getProject()['$id'], 
     'x-appwrite-key' => $this->getProject()['apiKey'], 
 ], []); 
 ```

2022-10-31 16:14 UTC, Meldiron commented
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

2022-10-31 18:48 UTC, stnguyen90 commented
@geisterfurz007 something seems off with the CI...Perhaps syncing with master would fix this?

2022-10-31 18:49 UTC, stnguyen90 requested changes
@geisterfurz007 something seems off with the CI...Perhaps syncing with master would fix this?

2022-10-31 21:05 UTC, geisterfurz007 commented
They ran through at least but a failure on a method I didn't touch 😕 I don't know if that's something that is looking familiar or if I should give it another shot locally tomorrow. What do you think @stnguyen90 ?

2022-11-02 21:37 UTC, stnguyen90 approved these changes
Seems like it was a flaky test. LGTM now! Thanks so much for this! 🙏🏼

2022-11-17 18:13 UTC, stnguyen90 commented
@TorstenDittmann or @christyjacob4, would you please merge when you get a chance?

2022-12-20 08:07 UTC, merged

2022-12-20 08:07 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)