update zh-tw translation
appwrite/appwrite pull request #4285
Opened 2022-10-04 12:32 UTC by vrabe

## What does this PR do?

Update traditional Chinese (zh-tw) translation.

## Test Plan

No

## Related PRs and Issues

Previous translation update: #112, #688, #2134

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2022-10-07 15:33 UTC, gewenyu99 commented
您好，这些改动是有什么讲究的吗？我自己是小时候在大陆生活过一段时间的，但是对于台湾的常用国语翻译不是很了解。

有没有什么您引用的文献之类的，我可以对照参考来做Review，会简单一点。

谢谢!

2022-10-07 15:53 UTC, vrabe commented
國名參照的是[CLDR](https://unicode-org.github.io/cldr-staging/charts/41/summary/zh_Hant.html#73c7c09de32184)。除了已經改名的北馬其頓(North Macedonia)外，基本上都是使用那邊的翻譯。

另外也有參考維基百科的[字詞轉換](https://zh.wikipedia.org/wiki/Module:CGroup/%E5%9C%B0%E5%90%8D)，我沒細看，但大致差不多。

2022-10-14 20:34 UTC, gewenyu99 requested changes
Reviewed translations against The Republic of China, Ministry of Foreign Affairs website. I want to make sure we avoid mistakes here and follow official naming guidelines.
https://www.mofa.gov.tw/CountryAreaInfo.aspx?casn=5&n=5&sms=33

2022-10-14 20:34 UTC, gewenyu99 commented on app/config/locale/translations/zh-tw.json
> +    "countries.la": "寮國",
```suggestion
    "countries.la": "寮人",
```

Source: https://www.mofa.gov.tw/CountryInfo.aspx?CASN=0&n=487&sms=33&s=157

2022-10-14 20:34 UTC, gewenyu99 commented on app/config/locale/translations/zh-tw.json
> +    "countries.kp": "北韓",
这边建议一起研究一下这个要不要改。这个比较敏感，而且与中华民国外交部使用的名称不符
https://www.mofa.gov.tw/CountryInfo.aspx?CASN=5&n=5&sms=33&s=48

2022-10-14 20:34 UTC, gewenyu99 commented on app/config/locale/translations/zh-tw.json
> +    "countries.sz": "史瓦濟蘭",
Actually, `史瓦帝尼`
According to: https://www.mofa.gov.tw/CountryInfo.aspx?CASN=0&n=487&sms=33&s=90

2022-10-15 08:26 UTC, vrabe commented on app/config/locale/translations/zh-tw.json
> +    "countries.la": "寮國",
The full name is 寮人民民主共和國. But we don't call it 寮人. You can check the tabs in that page.

2022-10-15 08:34 UTC, vrabe commented on app/config/locale/translations/zh-tw.json
> +    "countries.sz": "史瓦濟蘭",
Yes, the country has renamed to Eswatini. But the original text is [Swaziland](https://github.com/appwrite/appwrite/blob/master/app/config/locale/translations/en.json#L201). So I keep using `史瓦濟蘭`. I can also use `史瓦帝尼` as you recommended.

2022-10-15 10:38 UTC, vrabe commented on app/config/locale/translations/zh-tw.json
> +    "countries.kp": "北韓",
兩個名稱都有人用，以我的感覺北韓一詞比較常用，所以這樣改。當然也不能說原來的翻譯就是錯的，兩個名稱都可以理解，只是用北韓會比較熟悉。如果要改回去我也是可以接受的。

2022-10-15 10:41 UTC, vrabe commented
@gewenyu99 Thanks for reviewing! You must have checked a lot pages to review my change.

2022-10-17 19:03 UTC, gewenyu99 commented on app/config/locale/translations/zh-tw.json
> +    "countries.sz": "史瓦濟蘭",
I'd just update it at this point :D

I think both names would work, but for the sake of being with the times, let's use the new name,

2022-10-17 19:05 UTC, gewenyu99 commented on app/config/locale/translations/zh-tw.json
> +    "countries.kp": "北韓",
北韩就北韩吧，大概率不会有朝鲜用户用得到这个的 这个不改了

2022-10-17 19:05 UTC, gewenyu99 commented on app/config/locale/translations/zh-tw.json
> +    "countries.la": "寮國",
彳亍。只要符合你们口语化用法就可以了。

2022-12-19 21:01 UTC, merged

2022-12-19 21:02 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)