Update add-runtime.md
appwrite/appwrite pull request #4315
Opened 2022-10-07 04:08 UTC by tusharxoxoxo

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2022-10-07 17:10 UTC, tessamero commented
line 93 was fine originally
line 240 was also fine originally

Not able to approve this

2022-10-07 21:20 UTC, gewenyu99 requested changes

2022-10-07 21:20 UTC, gewenyu99 commented on docs/tutorials/add-runtime.md
> +5. Finally execute the function and handle whatever response the user's code returns. Try to wrap the function into a `try catch ` statement to handle any errors the user's function encounters and re
Please revert this change.

2022-10-07 21:20 UTC, gewenyu99 commented on docs/tutorials/add-runtime.md
> +    'tarname'  =>  'LANGUAGE_NAME-VERSION.tar.gz', // Note: If your version has a point in it replace it, with a dash instead for this value.
Please revert this change :)

2022-10-09 11:23 UTC, tusharxoxoxo commented on docs/tutorials/add-runtime.md
> +5. Finally execute the function and handle whatever response the user's code returns. Try to wrap the function into a `try catch ` statement to handle any errors the user's function encounters and re
done

2022-10-09 11:24 UTC, tusharxoxoxo commented on docs/tutorials/add-runtime.md
> +    'tarname'  =>  'LANGUAGE_NAME-VERSION.tar.gz', // Note: If your version has a point in it replace it, with a dash instead for this value.
reverted

2022-10-31 16:27 UTC, Meldiron commented
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

2022-11-17 19:44 UTC, stnguyen90 commented
@tusharxoxoxo, looks like there are merge conflicts. Would you please resolve them and then re-request a review.

2023-01-27 13:17 UTC, christyjacob4 approved these changes

2023-01-27 13:17 UTC, merged

2023-01-27 13:17 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)