Feat 4002 add snappy comporession
appwrite/appwrite pull request #4336
Opened 2022-10-08 15:56 UTC by shtelzerartem

## What does this PR do?

Adds Snappy compression adapter

## Test Plan

Added 2 tests for Snappy compression similarly to ZSTD, both passed tests

<img width="639" alt="Screen Shot 2022-10-08 at 18 48 53" src="https://user-images.githubusercontent.com/20266461/194716110-3d5def66-5d67-41da-85e9-95156473bf4a.png">
<img width="658" alt="Screen Shot 2022-10-08 at 18 48 37" src="https://user-images.githubusercontent.com/20266461/194716105-c82859cb-4a92-4e15-95bc-751049e02928.png">

 - [x] `testCreateBucketFileSnappyCompression`
 - [x] `testFilePreviewSnappyCompression`

## Related PRs and Issues

Resolves [#4002](https://github.com/appwrite/appwrite/issues/4002)
Relates to my second PR [#4002-utopia-php](https://github.com/utopia-php/storage/pull/56)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yep :)

2022-10-10 06:55 UTC, Meldiron commented
@shtelzerartem , thanks for the PR! 🤯 Please give us some time to review it.

2022-10-28 21:59 UTC, stnguyen90 requested changes
Looks good! I'm going to add the `hacktoberfest-accepted` label, but the core team will need to clean up some things before this can be merged:

- [ ] Update API specs
- [ ] Bump utopia-php/storage in composer.json
- [ ] Fix merge conflict

2023-01-27 12:15 UTC, christyjacob4 commented on composer.json
> +            "type": "git"
reminder to remove this

2023-01-27 12:32 UTC, christyjacob4 commented on app/views/console/storage/bucket.phtml
> +    data-service="storage.getBucket"
We need to remove this file. We no longer use it. You need to add the compression option here
https://github.com/appwrite/console/blob/72b3f26edb802517b8d1c9d02900dbb99da58d38/src/routes/console/project-%5Bproject%5D/storage/bucket-%5Bbucket%5D/settings/+page.svelte#L49

2023-01-27 12:32 UTC, christyjacob4 commented on app/controllers/api/storage.php
> +    ->param('compression', 'none', new WhiteList([COMPRESSION_TYPE_NONE, COMPRESSION_TYPE_GZIP, COMPRESSION_TYPE_ZSTD, COMPRESSION_TYPE_SNAPPY]), 'Compression algorithm choosen for compression. Can b
Please replace the string literals with the constants in all occurances in this file

2023-01-27 12:37 UTC, christyjacob4 requested changes
Please address the comments

2023-04-06 22:03 UTC, christyjacob4 commented
@shtelzerartem thanks a lot for your contributions during Hacktoberfest 2022! 

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord. 

I'm closing this PR as there has not been any activity on this for quite a while. If you'd like to continue working on it , feel free to create a new PR.

2023-04-06 22:03 UTC, closed without merging