fix: correctly handle `=` in .env
appwrite/appwrite pull request #4341
Opened 2022-10-09 06:00 UTC by megatank58

## What does this PR do?

This PR adds the limit argument to explode method to correctly handle `=` in .env files

## Test Plan

The code has been manually ran and tested against test case.

## Related PRs and Issues

Closes #4294 

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2022-10-13 23:03 UTC, stnguyen90 commented
@megatank58 Thanks for your PR! 🙏 To be fair during Hacktoberfest, we are only allowing the assignee to complete PRs for issues where we only need 1 submission. Please comment on the issue with your interest and we will assign the issue in the order received.

2022-10-14 19:31 UTC, stnguyen90 requested changes
Would you please add a test case for this?

2022-10-17 10:29 UTC, megatank58 commented
I've added the tests, do let me know if something is wrong.

2022-10-31 16:26 UTC, Meldiron commented
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

2022-11-18 00:41 UTC, stnguyen90 approved these changes
LGTM!

2022-11-18 00:42 UTC, stnguyen90 commented
@TorstenDittmann, what do you think?

2022-12-20 11:01 UTC, christyjacob4 approved these changes

2022-12-20 11:02 UTC, merged

2022-12-20 11:02 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)