Fix User not found exception
appwrite/appwrite pull request #4506
Opened 2022-10-14 16:27 UTC by karniv00l

## What does this PR do?

Currently, there's a bug with the way User not found exception is created. This PR fixes it.

<img width="1322" alt="Screenshot 2022-10-14 at 18 19 24" src="https://user-images.githubusercontent.com/3144291/195894026-8e6371c2-2456-4980-89cd-3969c4a26f3b.png">

<img width="1588" alt="Screenshot 2022-10-14 at 18 08 58" src="https://user-images.githubusercontent.com/3144291/195894363-342b0ec6-f381-4fdb-8b19-910c327f516f.png">

## Test Plan

You can see on the screenshot that `phpstan` recognizes it right away, however ideally there should be also a test case for this `if` statement. I'm not very familiar with the codebase, If anyone could point me to the appropriate test location, I could do it.

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you added your change to the [Changelog](https://github.com/appwrite/appwrite/blob/master/CHANGES.md)?

(The CHANGES.md file tracks all the changes that make it to the `main` branch. Add your change to this file in the following format)
- One line description of your PR [#pr_number](Link to your PR)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

yes

2022-10-14 17:13 UTC, stnguyen90 requested changes
@karniv00l, thanks for catching this! Would you also be able to add a test case for this?

https://github.com/karniv00l/appwrite/blob/833e3f8ce1c652a182a3fcb7d95098c9ac702d3c/tests/e2e/Services/Users/UsersBase.php#L646

2022-10-15 14:40 UTC, karniv00l commented
@stnguyen90 I've added missing test cases

2022-10-15 17:00 UTC, stnguyen90 requested changes

2022-10-15 17:00 UTC, stnguyen90 commented on tests/e2e/Services/Users/UsersBase.php
> +         * Test for USER NOT FOUND
To keep things consistent with other tests, let's call this Test for FAILURE

2022-10-15 18:57 UTC, karniv00l commented on tests/e2e/Services/Users/UsersBase.php
> +        /**
Done

2022-10-16 12:00 UTC, karniv00l commented
@stnguyen90 not sure why tests failed, should we try again?

2022-10-18 00:55 UTC, stnguyen90 approved these changes
@karniv00l Hey 👋 awesome work on your PR! We've approved your work and it'll be merged soon!

2022-12-20 07:55 UTC, christyjacob4 approved these changes

2022-12-20 07:55 UTC, merged

2022-12-20 07:55 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)