Fix 3918 change datetime hou cycle
appwrite/appwrite pull request #4561
Opened 2022-10-23 10:33 UTC by kumarav1nash

## What does this PR do?

This PR fixes the DateTime issue which is related to #3918

## Test Plan

This was a UI issue so took a screenshot of it after fixes.
<img width="795" alt="Screenshot 2022-10-23 at 4 02 41 PM" src="https://user-images.githubusercontent.com/36467023/197387215-4cfa5231-c799-4da5-8161-36f0f16336b7.png">

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

YES

2022-10-23 14:23 UTC, stnguyen90 requested changes
Great PR! 🤯 please remove the extra files added to the repo.

2022-10-23 14:23 UTC, stnguyen90 commented on appwrite/.env
> +_APP_ENV=production
Please remove this file

2022-10-23 14:23 UTC, stnguyen90 commented on appwrite/docker-compose.yml
> +x-logging: &x-logging
Please remove this file

2022-10-25 15:01 UTC, kumarav1nash commented on appwrite/.env
> +_APP_ENV=production
Done

2022-10-25 16:06 UTC, kumarav1nash commented
sure

2022-10-27 22:19 UTC, stnguyen90 approved these changes
Hey 👋 awesome work on your PR! We've approved your work and it'll be merged soon!

2022-11-17 17:42 UTC, stnguyen90 commented
Sorry, it looks like this isn't applicable anymore with the release of 1.1.0

2022-11-17 17:42 UTC, closed without merging