Update german translation
appwrite/appwrite pull request #4589
Opened 2022-10-27 06:53 UTC by SoftCreatR

Add missing language variables.

2022-10-27 07:43 UTC, SoftCreatR commented
@TorstenDittmann Is this supposed to fail? :D

2022-10-31 16:23 UTC, PineappleIOnic commented
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

2022-11-11 09:08 UTC, johannesschobel commented
LGTM

2022-11-17 06:10 UTC, stnguyen90 commented
@TorstenDittmann would you be able to review and merge this?

2023-01-27 21:54 UTC, TorstenDittmann requested changes

2023-01-27 21:54 UTC, TorstenDittmann commented on app/config/locale/translations/de.json
> +    "emails.certificate.body": "Das Zertifikat für Ihre Domain '{{domain}}' konnte nicht generiert werden. Dies ist der {{attempt}}. Versuch. Fehlermeldung: {{error}}",
```suggestion
    "emails.certificate.body": "Das Zertifikat für ihre Domain '{{domain}}' konnte nicht generiert werden. Dies ist der {{attempt}}. Versuch. Fehlermeldung: {{error}}",
```

2023-01-27 21:54 UTC, TorstenDittmann commented on app/config/locale/translations/de.json
> +    "emails.certificate.footer": "Ihr bisheriges Zertifikat ist noch 30 Tage nach Auftreten des ersten Fehlers gültig. Wir empfehlen dringend, diesen Vorfall zu untersuchen, da eine sichere Kommunika
```suggestion
    "emails.certificate.footer": "Ihr bisheriges Zertifikat ist noch 30 Tage nach Auftreten des ersten Fehlers gültig. Wir empfehlen dringend, diesen Vorfall zu untersuchen, da eine sichere Kommunikation mit ihrer Domain nach Ablauf des Zertifikats nicht mehr möglich sein wird.",
```

2023-01-29 17:52 UTC, SoftCreatR commented
@TorstenDittmann Wie kommst du denn darauf, dass bei der formellen Anrede `Ihre` klein geschrieben wird? Oder ist die Anrede hier grundsätzlich informell? Denn dann muss ich das Wording sowieso ändern.

2023-01-29 17:54 UTC, SoftCreatR commented
Vergiss die Frage wieder. Ich habe die Übersetzung damals ja selbst gemacht und die Anrede informell gehalten. Ich habe die Texte entsprechend überarbeitet.

2023-04-05 20:54 UTC, christyjacob4 commented
@SoftCreatR thanks a lot for your contributions during Hacktoberfest 2022! 

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord. 

2024-02-03 15:53 UTC, closed without merging