Include response of 5xx status codes for function executions
appwrite/appwrite pull request #4610
Opened 2022-10-30 10:13 UTC by ks129

## What does this PR do?

Include the function's response if the status code is >= 500.

## Test Plan

Run the function provided in the linked issue. Should include response now.

## Related PRs and Issues

Closes #4594 

### Have you added your change to the [Changelog](https://github.com/appwrite/appwrite/blob/master/CHANGES.md)?

Yes

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2023-01-07 16:42 UTC, stnguyen90 requested changes
Could you please fix the merge conflict?

2023-02-08 22:27 UTC, stnguyen90 approved these changes
Tested and a function like:

```python
def main(req, res):
  if not req.variables.get('APPWRITE_FUNCTION_ENDPOINT') or not req.variables.get('APPWRITE_FUNCTION_API_KEY'):
    print('Environment variables are not set. Function cannot use Appwrite SDK.')
  
  return res.json({
    "areDevelopersAwesome": True,
  }, 500)
  ```
  
  Will now return like:
  
  ```json
  {
    "$id": "63e420cd177213440e49",
    "$createdAt": "2023-02-08T22:23:09.096+00:00",
    "$updatedAt": "2023-02-08T22:23:12.416+00:00",
    "$permissions": [
        "read(\"user:63e41fccb0eecf38c5d6\")"
    ],
    "functionId": "test",
    "trigger": "http",
    "status": "failed",
    "statusCode": 500,
    "response": "{\"areDevelopersAwesome\":true}",
    "stdout": "Environment variables are not set. Function cannot use Appwrite SDK.\n",
    "stderr": "Internal Runtime error.",
    "duration": 0.08936
}
  ```
  
Hey 👋 awesome work on your PR! We've approved your work and it'll be merged soon!

2023-02-19 16:31 UTC, christyjacob4 approved these changes

2023-02-19 17:07 UTC, merged

2023-02-19 17:07 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)