Fix: Unknown Continent Issue for Locale API
appwrite/appwrite pull request #4761
Opened 2022-11-22 23:54 UTC by codercatdev

## What does this PR do?

Fixes the response on Locale API

## Test Plan

Manually changed the inbound IP `$ip = $request->getIP();` to my own and see continent returned.

## Related PRs and Issues

#4760 

### Have you added your change to the [Changelog](https://github.com/appwrite/appwrite/blob/master/CHANGES.md)?

Yes

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2022-11-22 23:59 UTC, codercatdev commented
Here is what I get when testing
<img width="707" alt="Screen Shot 2022-11-22 at 6 58 19 PM" src="https://user-images.githubusercontent.com/3102249/203444852-e4dcc3cc-8a33-41db-b312-33d3ef5e6322.png">

2022-11-23 00:20 UTC, stnguyen90 requested changes

2022-11-23 00:20 UTC, stnguyen90 commented on CHANGES.md
> +- Fix Locale API returning Unknown continent [#4761](https://github.com/appwrite/appwrite/pull/4761)
Version 1.1.1 has already been released so probably should go in a new section, 1.1.2

2022-11-23 17:53 UTC, TorstenDittmann approved these changes

2022-11-23 17:53 UTC, stnguyen90 approved these changes

2022-11-23 17:53 UTC, merged