fix: adds the missing expire attribute to ListSessions call
appwrite/appwrite pull request #4872
Opened 2022-12-16 20:39 UTC by CoderMayhem

## What does this PR do?

Adds the missing `expire` attribute to the ListSessions response. Linked to issue #4846 
## Test Plan

Changes were done as suggested in the issue discussion thread by @stnguyen90. I couldn't figure out a way to test it and would appreciate any help in setting up a dummy call to the API and check for ListSessions output.

## Related PRs and Issues

Fixes #4846 
### Have you added your change to the [Changelog](https://github.com/appwrite/appwrite/blob/master/CHANGES.md)?
Not yet

(The CHANGES.md file tracks all the changes that make it to the `main` branch. Add your change to this file in the following format)
- One line description of your PR [#pr_number](Link to your PR)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2023-01-10 20:58 UTC, stnguyen90 commented on app/controllers/api/account.php
> +            $session->setAttribute('expire', DateTime::addSeconds(new \DateTime($session->getCreatedAt()), $authDuration));
The value should be formatting like an ISO string as well.

2023-01-10 20:58 UTC, stnguyen90 requested changes
Great PR! 🤯 We left some comments during the review, please check them out.

2023-03-09 18:03 UTC, stnguyen90 commented
@CoderMayhem are you still able to work on this PR or should this be reassigned?

2023-03-09 18:10 UTC, CoderMayhem commented
Hey @stnguyen90, looks like I missed your comment. I apologize. I'll do the changes requested and push them.

2023-04-25 00:43 UTC, stnguyen90 commented
@CoderMayhem, how's your progress on this? Also, it looks like there's a merge conflict now.

2023-05-23 14:42 UTC, stnguyen90 commented
@CoderMayhem, FYI, I'll need to close this due to inactivity soon.

2023-06-01 22:15 UTC, closed without merging