Updates readme according to suggestions from editing agency
appwrite/appwrite pull request #4934
Opened 2022-12-29 21:49 UTC by gewenyu99

## What does this PR do?

This is a test run for grammar edits from an editing agency. This PR updates README.md following most, but not all suggestions from their edit.

## Test Plan

Manual Review

2022-12-29 22:18 UTC, stnguyen90 approved these changes

2022-12-30 06:33 UTC, eldadfux requested changes

2022-12-30 06:33 UTC, eldadfux commented on CONTRIBUTING.md
> +If you are worried or don’t know where to start, check out the next section that explains what kind of help we could use and where you can get involved. You can reach out with questions to [Eldad Fux
I think we can remove my name. This is from very early days. We can just add something generic instead.

2022-12-30 06:33 UTC, eldadfux commented on CONTRIBUTING.md
> +Appwrite's current structure is a combination of both [Monolithic](https://en.wikipedia.org/wiki/Monolithic_application) and [Microservice](https://en.wikipedia.org/wiki/Microservices) architectures,
```suggestion
Appwrite's current structure is a combination of both [Monolithic](https://en.wikipedia.org/wiki/Monolithic_application) and [Microservice](https://en.wikipedia.org/wiki/Microservices) architectures.
```

2022-12-30 06:33 UTC, eldadfux commented on CONTRIBUTING.md
> +Appwrite is follows the [PHP-FIG standards](https://www.php-fig.org/). Currently, we use both PSR-0 and PSR-12 for coding standards and autoloading standards.
Appwrite is follows?

2022-12-30 15:10 UTC, eldadfux approved these changes

2022-12-30 15:10 UTC, merged