Fix 4982 email session expire string formattz
appwrite/appwrite pull request #4985
Opened 2023-01-11 07:06 UTC by munyoudoum

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan
- added 2 assertions

## Related PRs and Issues

https://github.com/appwrite/appwrite/issues/4982
### Have you added your change to the [Changelog](https://github.com/appwrite/appwrite/blob/master/CHANGES.md)?

(The CHANGES.md file tracks all the changes that make it to the `main` branch. Add your change to this file in the following format)
- One line description of your PR [#pr_number](Link to your PR)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
Yes

2023-01-12 19:28 UTC, stnguyen90 requested changes
Great PR! 🤯 Would you please also check some other methods:

1. Create Magic URL session (confirmation)
2. Create Phone Session (confirmation)
3. Create Anonymous Session
4. Get Session
5. Update OAuth Session (Refresh Tokens)

2023-01-17 18:29 UTC, munyoudoum commented
Not sure when I'll be available to work on this.
If possible, you can merge it first and let others contribute the remaining methods because it also fixed the reported bug

2023-02-01 01:45 UTC, stnguyen90 approved these changes

2023-02-24 09:53 UTC, TorstenDittmann approved these changes

2023-02-24 09:54 UTC, merged

2023-03-28 08:13 UTC, karbonnanroid approved these changes

2023-03-28 08:14 UTC, karbonnanroid approved these changes