add restart policy for worker-messaging container
appwrite/appwrite pull request #4994
Opened 2023-01-12 07:02 UTC by aayushbisen

## What does this PR do?

It adds a restart policy in `appwrite-worker-messaging` service in `docker-compose.yml`

## Test Plan

This can be tested by restarting the machine where appwrite is deployed and checking the status of `appwrite-worker-messaging` container, the status should be running.

## Related PRs and Issues

#4986 

### Have you added your change to the [Changelog](https://github.com/appwrite/appwrite/blob/master/CHANGES.md)?

No

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2023-01-12 18:44 UTC, stnguyen90 requested changes
For consistency, would you please also update the root docker-compose.yml file?

https://github.com/appwrite/appwrite/blob/a35cf0b4c01fe5363cbad54cdb02a3f82f570b27/docker-compose.yml#L553

2023-01-14 09:41 UTC, aayushbisen commented
Updated the root compose file also.

2023-01-23 10:16 UTC, aayushbisen commented
@stnguyen90 let me know if anything else needs to be changed.

2023-01-26 00:41 UTC, stnguyen90 approved these changes

2023-01-27 12:21 UTC, merged