Update errors.php
appwrite/appwrite pull request #5136
Opened 2023-02-16 19:41 UTC by vedant-z

## What does this PR do?
Fixes #4519 
(Provide a description of what this PR does and why it's needed.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Screenshots may also be helpful.)

## Related PRs and Issues

- (Related PR or issue)

## Checklist

- [ ] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [ ] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

2023-02-16 19:42 UTC, vedant-z commented
@stnguyen90 Please review this

2023-03-14 23:32 UTC, stnguyen90 requested changes
Great PR! 🤯 We left some comments during the review, please check them out.

2023-03-14 23:32 UTC, stnguyen90 commented on tests/e2e/Services/Projects/ProjectsConsoleClientTest.php
> +         $id = $data['projectId'] ?? '';
Looks like there are style problems indicated by the lint errors. Would you please fix them so the CI job passes?

2023-07-19 15:20 UTC, stnguyen90 commented
@vedant-z, would you please run the formatter to fix the styling errors?

FYI, I'll need to close this due to inactivity soon.

2023-08-15 00:37 UTC, stnguyen90 commented
Closing due to inactivity

2023-08-15 00:37 UTC, closed without merging