Updates links for query page
appwrite/appwrite pull request #5301
Opened 2023-03-29 19:39 UTC by gewenyu99

## What does this PR do?

Update links to queries page because of changes here:
https://github.com/appwrite/docs/pull/342

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Screenshots may also be helpful.)

## Related PRs and Issues

- (Related PR or issue)

## Checklist

- [ ] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [ ] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

2023-04-05 00:42 UTC, stnguyen90 approved these changes
nice catch!

2023-04-07 21:01 UTC, christyjacob4 commented on Dockerfile
> +FROM appwrite/base:0.2.0 as final
```suggestion
FROM appwrite/base:0.2.2 as final
```

2023-04-07 21:05 UTC, christyjacob4 requested changes
Looks good. Just one comment

2023-04-10 15:08 UTC, christyjacob4 approved these changes

2023-04-11 05:15 UTC, abnegate approved these changes

2023-04-11 05:16 UTC, merged