Added Documentation change on static files
appwrite/appwrite pull request #5327
Opened 2023-04-08 16:43 UTC by pranjalg13

## What does this PR do?

I updated the documentation on building static files and redirecting to the correct repo.

## Test Plan

NA

## Related PRs and Issues

https://github.com/appwrite/appwrite/issues/5318

## Checklist

- [-] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [-] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it include updated API specs and example docs?

2023-04-20 09:24 UTC, ArmanNik submitted a review, later dismissed
Good catch! :blush: 
We might also want to link our [contribution guide](https://github.com/appwrite/console/blob/main/CONTRIBUTING.md) and invite people to contribute.

I would also mention that we use [Pink](https://github.com/appwrite/pink) for our CSS.

2023-04-20 18:20 UTC, gewenyu99 requested changes
Small comments :)

Thanks for catching this!

2023-04-20 18:20 UTC, gewenyu99 commented on CONTRIBUTING.md
> +Appwrite UI is built with two frameworks [Svelte](https://svelte.dev/) and [Svelte Kit](https://kit.svelte.dev/). You can refer the repo [Appwrite-Console](https://github.com/appwrite/console) to lea
```suggestion
Appwrite's UI is built with [Svelte](https://svelte.dev/), [Svelte Kit](https://kit.svelte.dev/), and the [Pink Design](https://github.com/appwrite/pink) component library. You can find the source code in the [Appwrite Console](https://github.com/appwrite/console) repository.
```

2023-04-20 18:20 UTC, gewenyu99 commented on CONTRIBUTING.md
> +To contribute to the UI, head over to the [Contribution Guide](https://github.com/appwrite/console/blob/main/CONTRIBUTING.md)
```suggestion
To contribute to the UI, head to the [Contribution Guide](https://github.com/appwrite/console/blob/main/CONTRIBUTING.md) of the Appwrite Console.
```

2023-04-25 21:41 UTC, gewenyu99 approved these changes

2023-05-09 15:04 UTC, TorstenDittmann approved these changes

2023-05-09 15:40 UTC, pranjalg13 commented
how is the test failing 😄 , is this because not synced with master? @gewenyu99 ?

2023-05-09 16:07 UTC, gewenyu99 commented
> how is the test failing 😄 , is this because not synced with master? @gewenyu99 ?

I wouldn't worry about it :P

2023-08-24 15:39 UTC, merged