Updated doc with correct endpoints
appwrite/appwrite pull request #5331
Opened 2023-04-10 22:43 UTC by x0samnan

## What does this PR do?

Fixes broken/unassigned links in doc.

## Test Plan

- Added new links in docfile
- Updated Broken links

## Related PRs and Issues

- Closes #5249 
- Cleaner PR of #5255 

## Checklist

- [ ✔️] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [ ✔️] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

2023-04-10 22:45 UTC, x0samnan commented
@gewenyu99 This is a cleaner PR of #5255 . @stnguyen90 I closed last PR because it got messed up.

2023-04-11 17:59 UTC, gewenyu99 requested changes
Hi there. Can you make this PR **just fixing broken links?**

There's many new `learn more about` links that link to themselves here.

2023-04-11 17:59 UTC, gewenyu99 commented on docs/references/account/create-session-email.md
> +Learn more about [create email session](/docs/client/account#accountCreateEmailSession).
Does this link to itself? 🤣

2023-04-11 17:59 UTC, gewenyu99 commented on docs/references/account/create-session-oauth2.md
> +Learn more about [Create OAuth2 session](/docs/client/account#accountCreateOAuth2Session).
Again I think this will link to itself!

2023-04-11 17:59 UTC, gewenyu99 commented on docs/references/account/delete-session.md
> +Learn more about how to [delete session](/docs/client/account#accountDeleteSession).
Ditto, self linking.

2023-04-11 20:43 UTC, x0samnan commented
@gewenyu99 I have removed the self-links.

2023-04-12 17:45 UTC, gewenyu99 commented on docs/references/account/delete-session.md
> +Use this endpoint to log out the currently logged in user from all their account sessions across all of their different devices. When using the Session ID argument, only the unique session ID provide
What changed here? I don't see a diff :P Github bug?

2023-04-12 17:46 UTC, gewenyu99 approved these changes
Looks good to me now :) Thank you for your help!!

2023-04-25 19:36 UTC, christyjacob4 commented on docs/tutorials/add-environment-variable.md
> +The environment variables in Appwrite are prefixed with `_APP_`. If it belongs to a specific category, the category name is appended as `_APP_REDIS` for the Redis category. The available categories a
we need to revert this change. The tutorials aren't really part of the website. So we cannot use relative links here

2023-04-25 19:36 UTC, christyjacob4 commented on docs/tutorials/add-oauth2-provider.md
> +You can test your OAuth2 provider by trying to login using the [OAuth2 method](/docs/client/account#accountCreateOAuth2Session) when integrating the Appwrite Web SDK in a demo app.
we need to revert this change. The tutorials aren't really part of the website. So we cannot use relative links here

2023-04-25 19:36 UTC, christyjacob4 requested changes
Please address the comments

2023-04-26 00:12 UTC, x0samnan commented
@christyjacob4 It is now resolved.

2024-12-11 19:04 UTC, christyjacob4 commented
Closing since its already updated on main https://github.com/appwrite/appwrite/blob/main/docs/references/account/create-email-verification.md

2024-12-11 19:04 UTC, closed without merging