Update Mail.php
appwrite/appwrite pull request #5495
Opened 2023-05-03 10:23 UTC by pechtelt1

## What does this PR do?

(Provide a description of what this PR does and why it's needed.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Screenshots may also be helpful.)

## Related PRs and Issues

- (Related PR or issue)

## Checklist

- [ ] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [ ] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

2023-05-03 22:12 UTC, stnguyen90 requested changes

2023-05-03 22:12 UTC, stnguyen90 commented on src/Appwrite/Event/Mail.php
> +        $this->name = $name ?? '';
I don't think this will work because according to the typing on the function, `$name` is a string and will never be `null`

2023-05-03 22:13 UTC, stnguyen90 commented
Please also provide some screenshot as a test that the change fixes the problem.

2023-05-31 06:48 UTC, pechtelt1 commented
@stnguyen90 thank you very much! The thing is that I don't have much experience here yet and am just starting this and I thought of just joining open source projects to learn but don't know exactly how to run this locally to test everything properly.

Apologies but as soon as I know more I am happy to help on other issues!

2023-06-15 18:51 UTC, stnguyen90 commented
@pechtelt1 you would have to start Appwrite and make the necessary API calls to trigger the endpoints. The contributing guide and docs should help you, but do you no longer want to work on this?

2023-06-16 07:29 UTC, pechtelt1 commented
@stnguyen90 i will try, thanks!

2023-06-23 08:17 UTC, pechtelt1 commented
It wont work for me... i hope someone else will able to fix it!

2023-06-28 14:54 UTC, stnguyen90 commented
@pechtelt1, if you cannot make progress on this, can I close it and have someone else work on it?

2023-06-29 15:01 UTC, closed without merging