Feat update project creation
appwrite/appwrite pull request #5572
Opened 2023-05-23 14:40 UTC by christyjacob4

## What does this PR do?

(Provide a description of what this PR does and why it's needed.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Screenshots may also be helpful.)

## Related PRs and Issues

- (Related PR or issue)

## Checklist

- [ ] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [ ] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

2023-05-23 21:36 UTC, eldadfux approved these changes

2023-05-23 23:58 UTC, stnguyen90 requested changes

2023-05-23 23:58 UTC, stnguyen90 commented on app/controllers/api/projects.php
> +        $collections = Config::getParam('collections', []);
Is this needed?

2023-05-24 20:07 UTC, christyjacob4 commented on app/controllers/api/projects.php
> +        $collections = Config::getParam('collections', []);
removed 👍

2023-05-25 15:28 UTC, stnguyen90 approved these changes

2023-05-25 17:20 UTC, merged