Update delete session description to be actually correct
appwrite/appwrite pull request #5707
Opened 2023-06-14 17:50 UTC by gewenyu99

## What does this PR do?

Related to https://github.com/appwrite/sdk-for-flutter/issues/153

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Screenshots may also be helpful.)

## Related PRs and Issues

- (Related PR or issue)

## Checklist

- [ ] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [ ] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

2023-06-15 00:53 UTC, lohanidamodar requested changes
suggested

2023-06-15 00:53 UTC, lohanidamodar commented on docs/references/account/delete-session.md
> +Logout the current user. Use 'current' as the session ID to logout on this device, or provide a specific session ID to target a different session.
May be, logout the user. Use `current` as the session ID to logout current user on this device ....?

2023-06-25 01:55 UTC, lohanidamodar approved these changes

2023-07-25 23:09 UTC, eldadfux approved these changes

2023-07-25 23:10 UTC, merged