fixed team creation response if teamId already exists
appwrite/appwrite pull request #5808
Opened 2023-07-12 17:37 UTC by jaivix

## What does this PR do?

Fixes the linked issue 

## Test Plan
- Created a simple web project, tried to create team with same teamId - 
<img width="729" alt="image" src="https://github.com/appwrite/appwrite/assets/124567525/e288879f-8bfd-42ff-abbf-48e2db4bcfea">

- Wrote test case for this - 
<img width="829" alt="image" src="https://github.com/appwrite/appwrite/assets/124567525/9faa1f03-febb-41c0-9d8c-e3acc9d9f0ae">

## Related PRs and Issues

- https://github.com/appwrite/appwrite/issues/5768

## Checklist

- [x] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [ ] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

2023-07-12 18:21 UTC, stnguyen90 requested changes
Great PR! 🤯 We left some comments during the review, please check them out.

Also, it looks like the linter failed. Please run the formatter to fix the lint error.

2023-07-12 18:21 UTC, stnguyen90 commented on src/Appwrite/Extend/Exception.php
> +    public const TEAM_ID_CONFLICT                  = 'team_id_conflict';
It's always good to take a look at existing code to try and match existing conventions. In this case, for other similar errors, we have `<RESOURCE>_ALREADY_EXISTS` such as `TEAM_INVITE_ALREADY_EXISTS`. So, this should probably be:

```suggestion
    public const TEAM_ALREADY_EXISTS                = 'team_already_exists';
```

2023-07-17 18:35 UTC, jaivix commented
not sure why test cases were failing since locally test cases seems to run fine, maybe because the repo wasn't synced with appwrite master, synced with master so this time the test cases should pass hopefully 🤞 
@stnguyen90 can you please review again.

2023-07-18 19:59 UTC, eldadfux approved these changes

2023-07-18 20:00 UTC, merged

2023-07-19 07:00 UTC, jaivix commented
thanks 🙏