changes : Added more documentation and grammatically fixed some.
appwrite/appwrite pull request #582
Opened 2020-10-01 00:10 UTC by relaxxpls

1. Corrected a few grammatical errors and typos in the docs/references/account/create-session-oauth2.md 
2. Added a general readme for all the OAuths, currently writing the individual readmes. Will add those using another pull request.

2020-10-01 03:52 UTC, eldadfux commented
Hey @relaxxpls, please submit the OAuth tutorial in this PR. We can't accept a PR with a link to a tutorial that does not exists yet. Thanks!

2020-10-01 19:19 UTC, relaxxpls commented
I've updated the pr adding the Google OAuth tutorial.

2020-10-06 17:18 UTC, relaxxpls commented
@eldadfux could you checkout this pr?

2020-10-07 09:47 UTC, Kolkies commented
Will look into this asap.

2020-10-08 10:20 UTC, Kolkies requested changes

2020-10-08 10:20 UTC, Kolkies commented on docs/oauth/OAuth-Google/README.md
> +Refrances:
I guess this should be `References`

2020-10-08 10:22 UTC, relaxxpls commented on docs/oauth/OAuth-Google/README.md
> +Refrances:
My bad, I'll fix it in a second!

2020-10-08 10:24 UTC, relaxxpls commented on docs/oauth/OAuth-Google/README.md
> +Refrances:
@Kolkies Done! Could you confirm?

2020-10-12 04:59 UTC, eldadfux commented
@relaxxpls a few things to fix:
1. Please use semantic titling, title needs to be in a logical hierarchy (h1 title => #, h2 title => ## and so on)
2. Please spell Appwrite and not AppWrite

2020-10-12 14:53 UTC, relaxxpls commented
> @relaxxpls a few things to fix:
> 
> 1. Please use semantic titling, title needs to be in a logical hierarchy (h1 title => #, h2 title => ## and so on)
> 2. Please spell Appwrite and not AppWrite

Will do soon!

2020-10-12 14:57 UTC, relaxxpls commented
@eldadfux changes have been made! Could you confirm?

2020-10-17 10:23 UTC, Kolkies commented on docs/oauth/OAuth-Google/README.md
> +## Features :
```suggestion
## Features:
```

2020-10-17 10:23 UTC, Kolkies commented on docs/oauth/OAuth-Google/README.md
> +## Functions Appwrite provides :
```suggestion
## Functions Appwrite provides:
```

2020-10-17 10:23 UTC, Kolkies commented on docs/oauth/README.md
> +## Choices AppWrite offers :
```suggestion
## Choices AppWrite offers:
```

2020-10-24 12:27 UTC, relaxxpls commented
@eldadfux @Kolkies if its done, could you merge this pr?

2022-05-04 23:44 UTC, closed without merging