Create a dedicated upgrade command
appwrite/appwrite pull request #5860
Opened 2023-07-21 18:29 UTC by stnguyen90

## What does this PR do?

Before, we used the same command for both installation and upgrades. This lead to problems because developers would try to upgrade in the wrong folder and end up creating a new installation.

This new upgrade command validates the existence of an existing installation before proceeding with the upgrade to ensure no new installation is created when upgrading.

## Test Plan

The following screenshot shows:

1. Running the upgrade command w/o an installation results in an error
2. After adding an installation (appwrite folder w/ docker-compose.yml file), the install command runs as usual
   * The error at the end occurs because I'm running in an appwrite instance where the docker socket is unavailable. When someone tries to upgrade, they will have the docker socket available and this error won't show.

<img width="1002" alt="Screen Shot 2023-07-20 at 7 11 29 PM" src="https://github.com/appwrite/appwrite/assets/1477010/9d46acea-f6d0-4e0f-b14c-9cfcc0db6752">

## Related PRs and Issues

- https://github.com/appwrite/appwrite/issues/2616

## Checklist

- [x] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [x] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

2023-07-22 13:38 UTC, eldadfux reviewed
@stnguyen90 this is not exactly how we use class based tasks, we've created a new abstraction layer for them here: https://github.com/appwrite/cloud/tree/feat-billing/src/Appwrite/Cloud/Platform/Tasks we might be able to reuse this logic as we need to rewrite them anyway.

Please check with @lohanidamodar if we can adapt this approach here.

2023-07-24 01:59 UTC, gewenyu99 requested changes
LGTM, but I want to add one word to feel useful.

(Jokes aside I think we should be verbose here.

2023-07-24 01:59 UTC, gewenyu99 commented on src/Appwrite/Task/Setup.php
> +            Console::log('Please navigate to the parent of the Appwrite installation and try again.');
```suggestion
            Console::log('Please navigate to the parent directory of the Appwrite installation and try again.');
```

2023-07-24 22:36 UTC, stnguyen90 commented
Need to restructure the task.

2023-07-24 22:36 UTC, closed without merging