Translated into Odia -od
appwrite/appwrite pull request #598
Opened 2020-10-01 10:07 UTC by prasanjit15

Hii,
I have translated the required files into the Odia language. Please merge it.

2020-10-02 08:15 UTC, spielers requested changes

2020-10-02 08:15 UTC, spielers commented on app/config/locale/translations/od.php
> +    'account.emails.verification.body' => 'en.email.auth.confirm.tpl',
you should change en.email.auth.confirm.tpl =>od.email.auth.confirm.tpl
similar with bellow all replace en. with your local language ISO code 

best,
spielers

2020-10-02 08:17 UTC, spielers commented
Thanks for your contributions, I would like to have some required changes @prasanjit15 

best,
spielers

2020-10-02 08:18 UTC, prasanjit15 commented
> Thanks for your contributions, I would like to have some required changes @prasanjit15
> 
> best,
> spielers

hmm give me a min will do the required

2020-10-02 08:22 UTC, prasanjit15 commented
@spielers have done the changes. You can verify it now

2020-10-03 04:59 UTC, prasanjit15 commented
@spielers will you please add the hacktoberfest-accepted label to the PR?

2020-10-04 07:01 UTC, spielers commented
@prasanjit15 Yeah we are on it.

2020-10-10 21:04 UTC, prasanjit15 commented
@spielers will this be merged?

2020-10-12 04:54 UTC, eldadfux commented
@prasanjit15 yes i'll merge this, but please update this 2 files as well:

**Configuration and Loading**
Add the new language to Appwrite config file: /app/config/locale/codes.php (order by ABC)
Load the new translation here: ./app/init.php (line: 224) (order by ABC)

2020-10-12 05:59 UTC, spielers commented
> @prasanjit15 yes i'll merge this, but please update this 2 files as well:
> 
> **Configuration and Loading**
> Add the new language to Appwrite config file: /app/config/locale/codes.php (order by ABC)
> Load the new translation here: ./app/init.php (line: 224) (order by ABC)

@prasanjit15  Follow the above Instructions Will get you merged!
best,
spielers

2020-10-12 06:04 UTC, prasanjit15 commented
@eldadfux  @spielers ok will do it

2020-10-12 17:09 UTC, prasanjit15 commented
> > @prasanjit15 yes i'll merge this, but please update this 2 files as well:
> > **Configuration and Loading**
> > Add the new language to Appwrite config file: /app/config/locale/codes.php (order by ABC)
> > Load the new translation here: ./app/init.php (line: 224) (order by ABC)
> 
> @prasanjit15 Follow the above Instructions Will get you merged!
> best,
> spielers

@spielers Kindly check PR [#673](https://github.com/appwrite/appwrite/pull/673) for the other changes @eldadfux  asked me to do. That is in continuation of this one.

2020-10-16 11:44 UTC, spielers commented
Hey, @prasanjit15 we should close This PR now #673  Got merged.

2020-10-16 11:48 UTC, prasanjit15 commented
Ok sure

2020-10-16 14:06 UTC, closed without merging