Fix Migrations Stability
appwrite/appwrite pull request #5998
Opened 2023-08-16 17:20 UTC by PineappleIOnic

## What does this PR do?

(Provide a description of what this PR does and why it's needed.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Screenshots may also be helpful.)

## Related PRs and Issues

- (Related PR or issue)

## Checklist

- [ ] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [ ] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

2023-08-16 17:51 UTC, eldadfux requested changes

2023-08-16 17:51 UTC, eldadfux commented on app/controllers/api/migrations.php
> +    ->param('subdomain', '', new Text(512), 'Source\'s Subdomain')
Can we use a host or domain validator instead? Why just a simple text, what do we expect here?

2023-08-16 17:51 UTC, eldadfux commented on src/Appwrite/Auth/OAuth2/Firebase.php
> +    function generateRandomString($length = 10)
Missing encapsulation.

2023-08-16 17:51 UTC, eldadfux commented on src/Appwrite/Auth/OAuth2/Firebase.php
> +    public function createCustomRole(string $accessToken, string $projectId): array
This has to be public?

2023-08-16 17:51 UTC, eldadfux commented on app/init.php
> +const APP_INTERNAL_LOOPBACK_HOST = 'appwrite';
```suggestion
const APP_HOSTNAME_INTERNAL = 'appwrite';
```

2023-08-16 18:08 UTC, PineappleIOnic commented on src/Appwrite/Auth/OAuth2/Firebase.php
> +    public function createCustomRole(string $accessToken, string $projectId): array
No it doesn't mb, changing to private

2023-08-17 09:51 UTC, eldadfux approved these changes

2023-08-18 10:28 UTC, merged