Added new testcase and modified duplicate domain error
appwrite/appwrite pull request #6019
Opened 2023-08-19 15:00 UTC by mustansirgodhrawala

## What does this PR do?

This PR addresses issue #4519, it performs two things.
1. Creates a new test case, for testing out duplicate domain for the same project and checks the error code. 
2. Modifies the previous error, to clearly state that the domain is the duplicate and not the id.
3. It fixes a previous test which lacked an assert statement

## Test Plan

I attempt to create a new project, with the same name as the one created in the previous test.

## Related PRs and Issues

- #4519 

## Checklist

- [x] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [x] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

2023-08-19 15:16 UTC, stnguyen90 requested changes
Great job! I left one comment. Also, it looks like there's a lint problem somewhere.

2023-08-19 15:16 UTC, stnguyen90 commented on app/config/errors.php
> +        'description' => 'A Domain with the requested NAME already exists.',
Name doesn't need to be all uppercase

2023-08-19 15:24 UTC, mustansirgodhrawala commented on app/config/errors.php
> +        'description' => 'A Domain with the requested NAME already exists.',
All good! Thanks for the input

2023-08-19 15:26 UTC, mustansirgodhrawala commented
All recommended changes complete, we should be good to go! Thanks for the help

2023-09-12 18:01 UTC, stnguyen90 commented
@mustansirgodhrawala sorry, but 1.4 made some changes to domains (replaced them with rules) so I don't think this is a problem anymore.

2023-09-12 18:01 UTC, closed without merging