Changes for Urdu Language
appwrite/appwrite pull request #609
Opened 2020-10-01 14:47 UTC by navneetsn18

Related to #25

@eldadfux @spielers  I have translated appwrite locale and email templates in Urdu.

Please review the changes and let me know if any fixes required.

2020-10-01 15:00 UTC, spielers commented
Hey, @navneetsn18 I suggest not editing the init.php file. I think that's causing a Build failure.

2020-10-01 15:30 UTC, navneetsn18 commented
Okk @spielers I will try to fix the issue..

2020-10-01 15:45 UTC, navneetsn18 commented
@spielers Now is it ok..

2020-10-01 16:09 UTC, spielers commented
@navneetsn18 Thanks now it's Fine.

2020-10-08 16:17 UTC, spielers requested changes

2020-10-08 16:17 UTC, spielers commented on app/config/locale/ur.countries.php
> +    'CD' => 'DR کانگو',
retranslate this

2020-10-12 05:02 UTC, eldadfux commented
Please update this 2 files as well:

Configuration and Loading
Add the new language to Appwrite config file: /app/config/locale/codes.php (order by ABC)
Load the new translation here: ./app/init.php (line: 224) (order by ABC)

2020-10-12 14:55 UTC, navneetsn18 commented on app/config/locale/ur.countries.php
> +    'CD' => 'DR کانگو',
From where to where..

2020-10-12 14:57 UTC, spielers commented on app/config/locale/ur.countries.php
> +    'CD' => 'DR کانگو',
'CD' => 'DR کانگو',

2020-10-12 17:39 UTC, navneetsn18 commented on app/config/locale/ur.countries.php
> +    'CD' => 'DR کانگو',
Ok i will fix that

2020-10-12 17:39 UTC, navneetsn18 commented
Ok sure @eldadfux

2020-10-13 07:34 UTC, navneetsn18 commented
@spielers @eldadfux I have made all the changes required please have a look.

2020-10-13 17:14 UTC, spielers approved these changes
Hey @navneetsn18 

Great job will get you merged !!

Bets,
spielers

2020-10-13 20:44 UTC, navneetsn18 commented
Thank you @spielers

2020-10-16 18:04 UTC, merged

2020-10-16 18:04 UTC, eldadfux commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like me to send you some cool Appwrite stickers and magnets! Please note that shipping might take longer times because of COVID19.

As a way of saying thank you, we have just invited you to join the Appwrite organization on GitHub. You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.