Remove Special Chars from Initials
appwrite/appwrite pull request #6164
Opened 2023-09-06 08:55 UTC by PineappleIOnic

## What does this PR do?

Remove Special Chars from Initials

## Checklist

- [x] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [ ] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

2023-09-28 14:43 UTC, stnguyen90 commented
Tested w/ `John (something) Doe` and got:

<img width="680" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/209aafb4-69f7-4afe-95d3-5e537f8820f2">

2023-09-28 15:08 UTC, stnguyen90 approved these changes

2023-09-28 15:11 UTC, christyjacob4 approved these changes

2023-09-29 01:28 UTC, stnguyen90 requested changes
It's working okay, but the tests seem to fail consistently. Would you please take a look at them?

2023-09-29 19:05 UTC, stnguyen90 approved these changes

2023-09-29 19:18 UTC, merged