Extracting function event validator to its own class.
appwrite/appwrite pull request #6219
Opened 2023-09-12 03:29 UTC by byawitz

## What does this PR do?
Closes #6218 

## Test Plan
1. Added `FunctionEventValidatorTest.php` which is the same as `EventValidatorTest.php` except that any event that starts with `functions.` will return false.
2. Tested it on a temporary local Appwrite instance, and I was able to add the `functions.*` events to a webhook but not to a function.

## Related PRs and Issues

#6218

## Checklist

- [X] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [X] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

2023-09-12 03:55 UTC, stnguyen90 requested changes
Would you please also uncomment the functions test in the event validator unit test?

2023-09-12 03:56 UTC, byawitz commented
Done

2023-09-12 18:25 UTC, stnguyen90 approved these changes

2023-09-13 02:36 UTC, abnegate approved these changes

2023-09-13 02:37 UTC, merged