Fix deployment delete
appwrite/appwrite pull request #6290
Opened 2023-09-21 02:34 UTC by stnguyen90

## What does this PR do?

Prior to this, deleting a VCS deployment would fail because the
deployment path for VCS deployments are empty. Because an error gets
thrown, the delete function would stop and not delete the build files.

This change updates the worker to only delete the storage files if the
path is set.

Fixes #6289

## Test Plan

Manually deleted a deployment:

<img width="805" alt="Screen Shot 2023-09-20 at 7 29 53 PM" src="https://github.com/appwrite/appwrite/assets/1477010/17476e6f-038f-42d5-9d4a-49ba4fac4601">

Manually deleted a function

<img width="839" alt="Screen Shot 2023-09-20 at 7 30 14 PM" src="https://github.com/appwrite/appwrite/assets/1477010/7d40e584-2cd3-4df5-a9b4-0abeff3324b4">

## Related PRs and Issues

- #6289

## Checklist

- [x] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [x] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

2023-09-21 06:21 UTC, Meldiron approved these changes

2023-09-21 20:11 UTC, TorstenDittmann approved these changes

2023-09-21 20:23 UTC, christyjacob4 commented on app/workers/deletes.php
> +        $this->deleteDeploymentFiles($storageFunctions, $document);
```suggestion
        $this->deleteDeploymentFiles($deviceFunctions, $document);
```

2023-09-21 20:23 UTC, christyjacob4 commented on app/workers/deletes.php
> +            $this->deleteBuildFiles($storageBuilds, $document);
```suggestion
            $this->deleteBuildFiles($deviceBuilds, $document);
```

2023-09-21 20:24 UTC, christyjacob4 commented on app/workers/deletes.php
> +            $this->deleteDeploymentFiles($storageFunctions, $document);
```suggestion
            $this->deleteDeploymentFiles($deviceFunctions, $document);
```

2023-09-21 20:24 UTC, christyjacob4 commented on app/workers/deletes.php
> +                $this->deleteBuildFiles($storageBuilds, $document);
```suggestion
                $this->deleteBuildFiles($deviceBuilds, $document);
```

2023-09-21 20:26 UTC, christyjacob4 requested changes
Looks Good 👌  Please address the comments

2023-09-22 15:37 UTC, christyjacob4 approved these changes

2023-09-22 15:37 UTC, merged