Update README.md
appwrite/appwrite pull request #6358
Opened 2023-09-29 09:48 UTC by LauraDuRy

Updated our follow us section. Added LinkedIn and our own blog.

## What does this PR do?

(Provide a description of what this PR does and why it's needed.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Screenshots may also be helpful.)

## Related PRs and Issues

- (Related PR or issue)

## Checklist

- [ ] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [ ] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

2023-09-29 09:49 UTC, eldadfux approved these changes

2023-10-02 18:20 UTC, gewenyu99 approved these changes

2023-10-23 16:23 UTC, stnguyen90 requested changes

2023-10-23 16:23 UTC, stnguyen90 commented on README.md
> +Join our growing community around the world! Check out our official [Blog](https://appwrite.io/blog). Follow us on [Twitter](https://twitter.com/appwrite), [LinkedIn](https://www.linkedin.com/company
Can you also update twitter to x?

2024-02-05 17:08 UTC, stnguyen90 commented on README.md
> +Join our growing community around the world! Check out our official [Blog](https://appwrite.io/blog). Follow us on [Twitter](https://twitter.com/appwrite), [LinkedIn](https://www.linkedin.com/company
Would you please update the Twitter mention here too?

```suggestion
Join our growing community around the world! Check out our official [Blog](https://appwrite.io/blog). Follow us on [X](https://twitter.com/appwrite), [LinkedIn](https://www.linkedin.com/company/appwrite/), [Dev Community](https://dev.to/appwrite) or join our live [Discord server](https://discord.gg/GSeTUeA) for more help, ideas, and discussions.
```

2024-02-16 16:07 UTC, stnguyen90 approved these changes

2024-02-16 16:08 UTC, stnguyen90 requested changes

2024-02-16 16:08 UTC, stnguyen90 commented on README.md
> +Join our growing community around the world! Check out our official [Blog](https://appwrite.io/blog). Follow us on [X](https://twitter.com/appwrite), [LinkedIn](https://www.linkedin.com/company/appwr
missing https:// for the discord link.

```suggestion
Join our growing community around the world! Check out our official [Blog](https://appwrite.io/blog). Follow us on [X](https://twitter.com/appwrite), [LinkedIn](https://www.linkedin.com/company/appwrite/), [Dev Community](https://dev.to/appwrite) or join our live [Discord server](https://appwrite.io/discord) for more help, ideas, and discussions.
```

2024-04-19 20:19 UTC, stnguyen90 approved these changes

2024-04-19 22:18 UTC, merged