feature-5232-Security-Scans-OSV-Scanner
appwrite/appwrite pull request #6506
Opened 2023-10-05 11:03 UTC by btme0011

## What does this PR do?

Added OSV-Scanner while pushing and raising pull_request

## Test Plan

1) Success test - 
![Screenshot 2023-10-05 at 4 10 20 PM](https://github.com/appwrite/appwrite/assets/71667635/51b97e81-4600-490a-a09e-4a28c7ee4030)

2) Failure test - 
![Screenshot 2023-10-05 at 3 51 20 PM](https://github.com/appwrite/appwrite/assets/71667635/2d160072-4ddb-42d3-a504-4be0ebe2249b)

## Related PRs and Issues

- #5232 

## Checklist

- [ ] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [ ] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

2023-10-13 23:15 UTC, stnguyen90 requested changes
Great PR! 🤯 We left some comments during the review, please check them out.

2023-10-13 23:15 UTC, stnguyen90 commented on .github/workflows/osv-scanner.yml
> +          osv-scanner -r .
Let's use this github action/workflow instead: https://google.github.io/osv-scanner/github-action/

2023-10-13 23:29 UTC, stnguyen90 requested changes

2023-10-13 23:29 UTC, stnguyen90 commented on .github/workflows/osv-scanner.yml
> +name: OSV Scanner
Let's change this to check-dependencies.yml and the name to Check dependencies

2024-04-08 20:21 UTC, gewenyu99 commented
Hey there! There were a lot of big PRs during this Hacktoberfest, and we wanted to give everyone ample time to collaborate with our engineering team. If you were able to merge your PRs during October, amazing. If it’s still not merged, don’t worry about it either. Either way, we’ve got your Hacktoberfest swag minted and ready to ship. 

Please comment with your Discord username here so we can contact you about your shipping information to deliver your Hacktoberfest swag.

2024-04-24 22:57 UTC, merged