Fixed hindi spellings of countries
appwrite/appwrite pull request #659
Opened 2020-10-06 15:16 UTC by tanishqchamola

Hi,
I have fixed the spellings of the country names in Hindi language. Please merge it.

2020-10-06 15:44 UTC, punitdiwan commented
@tanishqchamola The hindi spelling of Afganistan is अफ़ग़ानिस्तान, its not अफ़्गानिस्तान. Please add dot (nukta) in  ग. Please check in hindi version of Wikipedia about Afganistan.

2020-10-06 15:50 UTC, spielers requested changes

2020-10-06 15:50 UTC, spielers commented on app/config/locale/translations/hi.countries.php
> +    'CZ' => 'चेक गणराज्या',
गणराज्या = >गणराज्य

2020-10-06 15:50 UTC, spielers commented on app/config/locale/translations/hi.countries.php
> +    'CZ' => 'चेक गणराज्या',
Or we can use चेक गणतंत्र

2020-10-06 15:57 UTC, spielers commented
@tanishqchamola  Thanks for your contributions But I would suggest you follow [WIKIPEDIA ](https://hi.wikipedia.org/wiki/%E0%A4%B5%E0%A4%BF%E0%A4%B6%E0%A5%8D%E0%A4%B5_%E0%A4%95%E0%A5%87_%E0%A4%B8%E0%A4%AD%E0%A5%80_%E0%A4%A6%E0%A5%87%E0%A4%B6)guideline and translation

2020-10-06 16:02 UTC, spielers requested changes
Hey @tanishqchamola follow Wikipedia for more correction

2020-10-06 16:02 UTC, spielers commented on app/config/locale/translations/hi.countries.php
> +    'VC' => 'सन्त विंसेंट और ग्रेनेडाइंस',
सन्त ==> सेण्ट

2020-10-07 17:58 UTC, tanishqchamola commented
@spielers Fixed the mistakes, please take a look. :)

2020-10-08 04:45 UTC, spielers commented
Hey, @tanishqchamola  Thanks for your contribution. I would suggest you should have a look at our open issues #25 #546 
if you are aiming for hacktoberfest, according to new rules of hacktoberfest this PR is not considered as a valid PR 

Best,
spielers

2020-10-08 05:31 UTC, tanishqchamola commented
@spielers, I am glad that I could contribute but the first point in issue #25 stated that we can submit PRs with fixes and improvements. So I thought it would be valid for hacktoberfest.

![Screenshot 2020-10-08 at 10 58 09](https://user-images.githubusercontent.com/36632821/95418421-15f24080-0955-11eb-895b-00498242d3d7.png)

2020-10-08 05:36 UTC, spielers commented
Hey,
That is great point we have updated that list before hacktoberfeast newer
update. will update that list and issue ASAP

Thanks for your response

Best,
Spielers

On Thu, 8 Oct, 2020, 11:01 am TANISHQ CHAMOLA, <notifications@github.com>
wrote:

> @spielers <https://github.com/spielers>, I am glad that I could
> contribute but the first point in issue #25
> <https://github.com/appwrite/appwrite/issues/25> stated that we can
> submit PRs with fixes and improvements. So I thought it would be valid for
> hacktoberfest.
>
> [image: Screenshot 2020-10-08 at 10 58 09]
> <https://user-images.githubusercontent.com/36632821/95418421-15f24080-0955-11eb-895b-00498242d3d7.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/appwrite/appwrite/pull/659#issuecomment-705339557>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALO3RDVWNED4RTH3XV7VOPLSJVFCRANCNFSM4SGFLOQA>
> .
>

2020-10-09 10:26 UTC, spielers commented
hey, @tanishqchamola  You got you covered I had a discussion With the maintainer team, will get you merged asap

2020-10-09 10:42 UTC, merged

2020-10-09 10:42 UTC, eldadfux commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like me to send you some cool Appwrite stickers and magnets! Please note that shipping might take longer times because of COVID19.

As a way of saying thank you, we have just invited you to join the Appwrite organization on GitHub. You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

2020-10-09 13:40 UTC, tanishqchamola commented
Thanks a lot @eldadfux. Will connect to you on discord. 👍