made the necessary changes to od
appwrite/appwrite pull request #673
Opened 2020-10-12 17:06 UTC by prasanjit15

Made the necessary changes and faced some issues while automatic merging. So, this is a new PR in continuation to my first PR [#598](https://github.com/appwrite/appwrite/pull/598)

2020-10-12 17:07 UTC, prasanjit15 commented
@spielers @eldadfux  I have faced some issues in auto merging of the PR and hence created this new PR in continuation to my first PR.

2020-10-12 17:38 UTC, spielers commented
@prasanjit15 Please resolve the conflict 

best,
spielers

2020-10-12 18:00 UTC, prasanjit15 commented
@spielers  I think the conflict is because it cannot find "od" files mentioned which may get resolved when my previous PR gets accepted.

2020-10-12 20:02 UTC, eldadfux commented
@prasanjit15 we must have all the changes in a single PR for the tests to pass, and for us to know the changes don't break the server.

2020-10-13 03:31 UTC, spielers commented
> @spielers I think the conflict is because it cannot find "od" files mentioned which may get resolved when my previous PR gets accepted.

Hey, @prasanjit15 You can merge all this in a single PR, so we can test all these

best,
spielers

2020-10-13 03:58 UTC, prasanjit15 commented
@spielers will do it but kindly don't do anything to the previous PR as this one will again take 14 days to review and I might as well miss the hacktoberfest goodies.

2020-10-13 04:10 UTC, spielers commented
> @spielers I will do it but kindly don't do anything to the previous PR as this one will again take 14 days to review and I might as well miss the hacktoberfest goodies.

Yeah don't worry dude we are here to help You 
Best,
spielers

2020-10-13 04:30 UTC, prasanjit15 commented
Sure, I will do it as soon as possible

2020-10-13 08:53 UTC, prasanjit15 commented
@spielers @eldadfux do check this.

2020-10-13 17:09 UTC, spielers requested changes

2020-10-13 17:09 UTC, spielers commented on app/config/locale/translations/od.php
> +    'account.emails.verification.body' => 'en.email.auth.confirm.tpl',
replace this to `od.email.auth.confirm.tpl'

2020-10-13 17:09 UTC, spielers commented on app/config/locale/translations/od.php
> +    'account.emails.recovery.body' => 'en.email.auth.recovery.tpl',
replace this to `od.email.auth.recovery.tpl'

2020-10-13 17:09 UTC, spielers commented on app/config/locale/translations/od.php
> +    'account.emails.invitation.body' => 'en.email.auth.invitation.tpl',
replace this to `od.email.auth.invitation.tpl'

2020-10-13 17:12 UTC, spielers commented
Hey @prasanjit15  please do the suggested changes

Best,
spielers

2020-10-13 17:51 UTC, prasanjit15 commented
Sure...i checked it twice but still missed it..sorry will do it

2020-10-13 18:13 UTC, spielers commented
Hey, @prasanjit15  Both the PRs #598  and #673  are some right. could you clarify The purpose of this?.

Best,
spielers

2020-10-13 18:27 UTC, prasanjit15 commented
@spielers As I said yesterday... When I did the changes that you and @eldadfux asked me to. The previous PR didn't got updated. I tried deleting the changes and did again but still nothing got updated. So, I thought maybe if I deleted the previous forked repo and fork once again the PR might get updated but unfortunately it didn't. So I have to create this again. ( Never did this type of thing before, as this is my first so faced this problem ). That is the reason I requested you yesterday if you are ok if I update the new PR with the same old PR and not to do anything with the old PR as I didn't want to loose my hacktoberfest goodies because of the 14 day review period which will start again with this new PR.

2020-10-14 07:26 UTC, prasanjit15 commented
@spielers I dont think any changes is required further. Please check again I think the changes you have asked to do had already been done. Please check again. All are already in od.

![image](https://user-images.githubusercontent.com/52557347/95956971-b0062d00-0e1c-11eb-8de5-c16b0348f902.png)

2020-10-14 07:32 UTC, spielers commented
Will check soon !

2020-10-14 07:33 UTC, prasanjit15 commented
Sure, Let me know if any further improvement has to be done. Thanks!

2020-10-14 14:59 UTC, spielers approved these changes
Hey, @prasanjit15 Thanks for contributions will get you merged !!!

Best,
Spielers

2020-10-14 15:00 UTC, prasanjit15 commented
Thanks

2020-10-15 05:07 UTC, merged

2020-10-15 05:07 UTC, eldadfux commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like me to send you some cool Appwrite stickers and magnets! Please note that shipping might take longer times because of COVID19.

As a way of saying thank you, we have just invited you to join the Appwrite organization on GitHub. You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.