feature-5232-Security-Scans-Kics
appwrite/appwrite pull request #6837
Opened 2023-10-07 05:41 UTC by btme0011

## What does this PR do?

Run Kics Scan

## Test Plan

Kicks Scan is able to execute the scan successfully but it fails due to following errors [links](https://github.com/btme0011/appwrite/actions/runs/6424134013/job/17444111351). 

As discussed with [steven](https://github.com/appwrite/appwrite/issues/5232#issuecomment-1749800528). Create a seperate issue for that -> [link](https://github.com/appwrite/appwrite/issues/6836)

## Related PRs and Issues

- #5232 

## Checklist

- [ ] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [ ] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

2023-10-13 23:19 UTC, stnguyen90 reviewed
Great PR! 🤯 We left some comments during the review, please check them out.

2023-10-13 23:19 UTC, stnguyen90 commented on .github/workflows/kicks-scan.yml
> +          path: ./Dockerfile
So this only scans our Dockerfile? Can we scan the whole repo?

2023-10-13 23:30 UTC, stnguyen90 requested changes

2023-10-13 23:30 UTC, stnguyen90 commented on .github/workflows/kicks-scan.yml
> +name: Scan for misconfigurations
Would you please rename the file to scan-misconfigurations.yml?

2023-11-13 23:56 UTC, tessamero commented
@btme0011 

Thank you for your contribution to Hacktoberfest 2023! We've noticed that your PR is still pending and requires some updates based on our engineering team's feedback.

We would love to see your PR successfully merged and send you the Appwrite swag as a token of appreciation. To remain eligible for the swag, please address the pending suggestions and/or ensure the tests pass  by **Friday, November 17th**. If the PR isn't updated by then, we will unfortunately have to close it due to the end of the Hacktoberfest event.

Looking forward to your updates and thank you!

2024-04-08 20:18 UTC, gewenyu99 commented
Hey there! There were a lot of big PRs during this Hacktoberfest, and we wanted to give everyone ample time to collaborate with our engineering team. If you were able to merge your PRs during October, amazing. If it’s still not merged, don’t worry about it either. Either way, we’ve got your Hacktoberfest swag minted and ready to ship. 

Please comment with your Discord username here so we can contact you about your shipping information to deliver your Hacktoberfest swag.

2024-08-27 04:44 UTC, stnguyen90 commented
Closing since we don't need to scan this.

2024-08-27 04:44 UTC, closed without merging