feature-5232-Trivy-Security-Scans
appwrite/appwrite pull request #6876
Opened 2023-10-10 13:04 UTC by btme0011

## What does this PR do?

Added Trivy scan

## Test Plan

Ran the scan on my personal forked Repo [link](https://github.com/btme0011/appwrite/actions/runs/6469467182/job/17563582936)

## Related PRs and Issues

- #5232 
## Checklist

- [ ] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [ ] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

2023-10-10 13:10 UTC, btme0011 commented
Currently the scan is failing Created an issue for it - [link](https://github.com/appwrite/appwrite/issues/6877)

2023-10-13 23:25 UTC, stnguyen90 requested changes
Great PR! 🤯 We left some comments during the review, please check them out.

2023-10-13 23:25 UTC, stnguyen90 commented on .github/workflows/trivy.yml
> +
```suggestion
```

2023-10-13 23:25 UTC, stnguyen90 commented on .github/workflows/trivy.yml
> +      run: docker build . -t appwrite_image:latest
Let's build like how we do in tests to make use of caching: 

https://github.com/appwrite/appwrite/blob/fce18647d2352e4cfce7ce75fd103a21bafbf7d0/.github/workflows/tests.yml#L28-L44

2023-10-13 23:25 UTC, stnguyen90 commented on .github/workflows/trivy.yml
> +name: Trivy
Let's name the file scan-container.yml and make this name Scan container. The workflow and goal is to have scans for containers and trivy is just a tool that may get swapped out later.

2024-04-08 20:17 UTC, gewenyu99 commented
Hey there! There were a lot of big PRs during this Hacktoberfest, and we wanted to give everyone ample time to collaborate with our engineering team. If you were able to merge your PRs during October, amazing. If it’s still not merged, don’t worry about it either. Either way, we’ve got your Hacktoberfest swag minted and ready to ship. 

Please comment with your Discord username here so we can contact you about your shipping information to deliver your Hacktoberfest swag.

2024-08-01 22:42 UTC, EVDOG4LIFE commented
Refactored this into a nightly running job that builds the image from source and runs a filesystem scan to scan for potential code vulnerabilities. 

Sample of what they look like - https://github.com/EVDOG4LIFE/appwrite_wfTest/security/code-scanning

FS and Image scan happen in parallel - see successful run on my fork here - https://github.com/EVDOG4LIFE/appwrite_wfTest/actions/runs/10206787738

2024-08-21 06:26 UTC, stnguyen90 approved these changes

2024-08-21 06:26 UTC, merged