add support endpoint URL for S3
appwrite/appwrite pull request #7172
Opened 2023-11-18 12:10 UTC by schneidermr

## What does this PR do?

Optionally can define an endpoint URL to make the S3 storage more generic and now able to support other S3 compatible API storage

## Test Plan

Use the new _APP_STORAGE_S3_ENDPOINT_URL environment variable to define any S3 storage API. In example, you can test it with Cloudflare R2. First setup the R2 in an account and after that use the same endpoint URL as described in the docs: <ACCOUNT_ID>.r2.cloudflarestorage.com

## Related PRs and Issues

https://github.com/appwrite/appwrite/issues/3352

## Checklist

- [x] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [x] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

2023-11-18 12:16 UTC, schneidermr commented
This changes also depends on the utopia storage module's change:
https://github.com/utopia-php/storage/pull/103

2023-11-18 13:05 UTC, schneidermr commented
And here are the changes related to the documentation: https://github.com/appwrite/website/pull/361

2024-08-04 06:29 UTC, jeffdrumgod commented
up

2024-10-25 15:04 UTC, salah-taha commented
This Must be merged!!

2024-10-25 15:09 UTC, salah-taha commented
@eldadfux

2024-11-01 19:05 UTC, schneidermr commented
JFYI I created this PR almost one year ago, so if the team wants to merge it finally a team member let me know on Discord (my username is futurmaster) and I'll update the branch otherwise I won't spend more unnecessary time on it

2024-11-22 07:12 UTC, lohanidamodar requested changes
This is great. Thank you @schneidermr for your contributions. 
Let's change the env name and then sync with main.

2024-11-22 07:12 UTC, lohanidamodar commented on .env
> +_APP_STORAGE_S3_ENDPOINT_URL=
Let's change this
```suggestion
_APP_STORAGE_S3_ENDPOINT=
```

2024-12-10 17:43 UTC, eldadfux requested changes

2024-12-10 17:43 UTC, eldadfux commented on docker-compose.yml
> +      - _APP_STORAGE_S3_ENDPOINT=
```suggestion
      - _APP_STORAGE_S3_ENDPOINT
```

2024-12-10 17:43 UTC, eldadfux commented on docker-compose.yml
> +      - _APP_STORAGE_S3_ENDPOINT=
```suggestion
      - _APP_STORAGE_S3_ENDPOINT
```

2024-12-10 17:43 UTC, eldadfux commented on docker-compose.yml
> +      - _APP_STORAGE_S3_ENDPOINT=
```suggestion
      - _APP_STORAGE_S3_ENDPOINT
```

2025-01-21 22:54 UTC, DH-555 approved these changes

2025-01-22 01:48 UTC, FabricSoul commented
plz merge this, we need to use this with self-hosted s3 servers

2025-01-22 06:57 UTC, salah-taha approved these changes

2025-01-22 22:58 UTC, schneidermr commented
I’m closing this PR because of the incompetency of the team. This was a good example for why no one should never try to make any contribution. Not the Appwrite team nor the CEO don’t really take any care of the contributors’ efforts.

2025-01-22 22:58 UTC, closed without merging

2025-01-26 09:40 UTC, eldadfux commented
This is a big failure on our side. We've been too caught up in dealing with urgent issues and weren't able to address this and some other PRs properly and this should not be the case. We're looking at ways to improve our processes and the team will work to get this feature included in the next release.

2025-04-17 17:50 UTC, sansavision commented
Damn.. I really needed this. Appwrite you're so trash for letting this gold sit idle for 2 YEARS!!!!!!!!