Fix link to queries documentation
appwrite/appwrite pull request #7186
Opened 2023-11-20 22:38 UTC by gewenyu99

## What does this PR do?

Fix links to queries documentation, related to https://github.com/appwrite/appwrite/issues/6371
## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Screenshots may also be helpful.)

## Related PRs and Issues

- (Related PR or issue)

## Checklist

- [ ] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [ ] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

2023-11-21 00:02 UTC, stnguyen90 requested changes
Would you please also generate the specs?

2023-11-21 00:02 UTC, stnguyen90 commented on package-lock.json
> +{
Let's not include this.

2023-11-29 16:33 UTC, gewenyu99 commented on package-lock.json
> +{
Done

2023-12-21 00:12 UTC, stnguyen90 approved these changes

2024-02-09 21:40 UTC, closed without merging