File tokens
appwrite/appwrite pull request #7329
Opened 2023-12-25 07:13 UTC by lohanidamodar

## What does this PR do?

(Provide a description of what this PR does and why it's needed.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Screenshots may also be helpful.)

## Related PRs and Issues

- (Related PR or issue)

## Checklist

- [ ] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [ ] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

2023-12-30 23:29 UTC, eldadfux requested changes

2023-12-30 23:29 UTC, eldadfux commented on app/config/collections.php
> +    'fileTokens' => [
Didn't we discuss the potential to make this a global feature at some point? Can we make the collection more general or use the existing structure for collections?

2024-07-15 13:35 UTC, moshOntong-IT commented
Does the file token is include to the URL or in headers?

2025-04-16 07:53 UTC, closed without merging

2025-04-16 07:53 UTC, lohanidamodar commented
moved to: https://github.com/appwrite/appwrite/pull/8997