Usage queue poc
appwrite/appwrite pull request #7503
Opened 2024-01-28 10:13 UTC by shimonewman

2024-02-04 20:09 UTC, eldadfux requested changes

2024-02-04 20:09 UTC, eldadfux commented on src/Appwrite/Platform/Workers/UsageDump.php
> +                                //Todo debug (to be removed later @shimon)
Remove left overs

2024-02-08 07:34 UTC, christyjacob4 commented on src/Appwrite/Platform/Workers/Usage.php
> +    private const KEYS_SENT_THRESHOLD = 60;
Lets increase these values

2024-02-08 07:39 UTC, christyjacob4 commented on src/Appwrite/Platform/Workers/Usage.php
Add a todo that we still need to handle the case of deployments performed when usage us being aggregated.

2024-02-08 07:47 UTC, christyjacob4 commented on src/Appwrite/Platform/Workers/Usage.php
Add another Todo to refactor the names of the two usage workers

2024-02-08 07:51 UTC, christyjacob4 commented on src/Appwrite/Platform/Workers/Usage.php
> +    private const KEYS_SENT_THRESHOLD = 60;
Lets use this  variable we already have
 $interval = (int) App::getEnv('_APP_USAGE_AGGREGATION_INTERVAL', '60000');

2024-02-08 07:54 UTC, christyjacob4 commented on app/controllers/api/users.php
> +        $affected = $dbForProject->deleteDocument('users', $userId);
Lets move this change to a separate PR, where we can apply this change to all the endpoints that require it

2024-02-08 07:55 UTC, christyjacob4 commented on docker-compose.yml
> +      #- ./vendor/utopia-php/database:/usr/src/code/vendor/utopia-php/database
lets remove this line

2024-02-08 09:04 UTC, christyjacob4 approved these changes

2024-02-09 14:42 UTC, merged