usage sms per country code count
appwrite/appwrite pull request #7592
Opened 2024-02-15 08:10 UTC by shimonewman

2024-02-15 14:26 UTC, christyjacob4 commented on src/Appwrite/Platform/Workers/Messaging.php
> +                console::error("Error parsing number: " . $e->getMessage());
```suggestion
                Console::error("Error parsing number: " . $e->getMessage());
```

2024-02-15 14:27 UTC, christyjacob4 commented on src/Appwrite/Platform/Workers/Messaging.php
> +            } catch (\libphonenumber\NumberParseException $e) {
lets import the exception and use `NumberParseException` directly

2024-02-18 21:13 UTC, eldadfux requested changes

2024-02-18 21:13 UTC, eldadfux commented on app/init.php
> +const METRIC_MESSAGES_COUNTRY_CODE  = '{countryCode}.messages';
```suggestion
const METRIC_MESSAGES_COUNTRY  = '{countryCode}.messages';
```

Code can be the value, we don't need as a prefix.

2024-02-18 21:13 UTC, eldadfux commented on src/Appwrite/Platform/Workers/Messaging.php
> +use libphonenumber\PhoneNumberUtil;
Let's not use the lib directly in Appwrite and instead abstract it in utopia/messaging.

2024-05-22 12:48 UTC, christyjacob4 approved these changes
Lets resolve the conflicts and merge 👍

2024-05-22 13:30 UTC, merged