React Native SDK
appwrite/appwrite pull request #7776
Opened 2024-03-10 03:48 UTC by lohanidamodar

## What does this PR do?

- React Native SDK

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Screenshots may also be helpful.)

## Related PRs and Issues

- https://github.com/appwrite/sdk-generator/pull/794

## Checklist

- [x] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [x] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

2024-03-10 17:00 UTC, gewenyu99 requested changes

2024-03-10 17:00 UTC, gewenyu99 commented on docs/sdks/react-native/GETTING_STARTED.md
> +From the options, choose to add a **Web** platform and add your client app hostname. By adding your hostname to your project platform you are allowing cross-domain communication between your project
```suggestion
If this is your first time using Appwrite, create an account and create your first project.

Then, under **Add a platform**, add a **Android app** or a **Apple app**. You can skip optional steps.

#### iOS steps
Add your app **name** and **Bundle ID**. You can find your **Bundle Identifier** in the **General** tab for your app's primary target in XCode.

#### Android steps
Add your app's **name** and **package name**, Your package name is generally the **applicationId** in your app-level [build.gradle](https://github.com/appwrite/playground-for-flutter/blob/master/android/app/build.gradle#L41) file.
```

2024-03-10 17:00 UTC, gewenyu99 commented on docs/sdks/react-native/GETTING_STARTED.md
> +    .setPlatform('com.example.myappwriteapp') // YOUR application ID
```suggestion
    .setPlatform('com.example.myappwriteapp') // Your application ID or bundle ID.
```

2024-03-10 17:00 UTC, gewenyu99 commented on docs/sdks/react-native/GETTING_STARTED.md
> +- 🚀 [Getting Started Tutorial](https://appwrite.io/docs/getting-started-for-react-native)
```suggestion
- 🚀 [Getting Started Tutorial](https://appwrite.io/docs/quick-starts/react-native)```

2024-04-29 10:08 UTC, abnegate approved these changes

2024-04-29 22:17 UTC, stnguyen90 approved these changes

2024-05-01 07:52 UTC, abnegate commented on app/config/platforms.php
> +                'beta' => false,
Should we start with beta?

2024-05-05 05:24 UTC, merged