Feat 8003 missing country for locale endpoint Palestine  Add new country Taiwan with its translations
appwrite/appwrite pull request #8031
Opened 2024-04-26 22:26 UTC by xuelink

## What does this PR do?

This PR adds a new country to the locale endpoint, providing all the necessary translations.

Fixes #8003

## Test Plan

Github Action will test the new country.

## Related PRs and Issues

- #8003

## Checklist

- [x] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [x] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

2024-04-30 21:56 UTC, stnguyen90 requested changes
Please fix failing locale tests.

2024-05-05 12:45 UTC, xuelink commented
> Please fix failing locale tests.

@stnguyen90 You can run this test again, i just fixed and committed for failing test.

2024-05-14 07:33 UTC, xuelink commented
@stnguyen90 What do you think that this PR gonna be merged before v1.5.6 ? Best

2024-05-14 23:50 UTC, stnguyen90 approved these changes

2024-05-14 23:50 UTC, merged