fix: updated typo in credit-cards.php credit card image filename
appwrite/appwrite pull request #8074
Opened 2024-05-04 11:46 UTC by infysumanta

## What does this PR do?

Its fixed double typo in credit card enum and image avatar

## Test Plan

Tested on local deployment environment

## Related PRs and Issues

- #8073 

## Checklist

- [x] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [x] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

2024-05-06 19:06 UTC, stnguyen90 requested changes

2024-05-06 19:06 UTC, stnguyen90 commented on app/config/avatars/credit-cards.php
> +    'cencosud' => ['name' => 'Consosud', 'path' => __DIR__ . '/credit-cards/cencosud.png'],
The name is still incorrect.

2024-05-06 19:07 UTC, stnguyen90 commented
@infysumanta, please also make sure to comment in the original issue to ask to be assigned on the issue.

2024-05-06 19:15 UTC, infysumanta commented
Thank you, @stnguyen90. Actually, I am new to the contribution journey. I will make sure to ask before raising a PR and will fix the spelling and update it.

2024-05-06 19:23 UTC, infysumanta commented on app/config/avatars/credit-cards.php
> +    'cencosud' => ['name' => 'Consosud', 'path' => __DIR__ . '/credit-cards/cencosud.png'],
updated the name, thanks

2024-05-07 17:43 UTC, stnguyen90 approved these changes

2024-05-07 17:43 UTC, merged