Unified Config logger
appwrite/appwrite pull request #8087
Opened 2024-05-07 13:45 UTC by byawitz

## What does this PR do?

(Provide a description of what this PR does and why it's needed.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Screenshots may also be helpful.)

## Related PRs and Issues

- (Related PR or issue)

## Checklist

- [x] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [x] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

2024-05-20 17:06 UTC, christyjacob4 commented on app/init.php
> +        };
https://github.com/utopia-php/logger/pull/37 

We changed the sentry & other constructors a bit to accept the parameters explicitly. We might want to adapt this PR to those changes.

2024-05-20 17:07 UTC, christyjacob4 commented on docker-compose.yml
> -      - _APP_LOGGING_CONFIG
We should remove all occurrences of _APP_LOGGING_PROVIDER from the compose file as well as compose.phtml

2024-05-20 17:08 UTC, christyjacob4 requested changes
Let's also change the target branch to 1.6.x

2024-05-23 04:12 UTC, stnguyen90 commented
Whoa there are a bit too many commits in this PR. maybe something else needs to be merged first...or some commits need to be removed 😬

2024-05-23 04:12 UTC, stnguyen90 reviewed
Whoa there are a bit too many commits in this PR. maybe something else needs to be merged first...or some commits need to be removed 😬

2024-05-23 16:46 UTC, byawitz commented
@stnguyen90 here's a concise version of it #8087

2024-05-23 16:46 UTC, closed without merging