Adding hk in translations
appwrite/appwrite pull request #8179
Opened 2024-05-22 11:18 UTC by navjotNSK

## What does this PR do?

It adds the hongkong in all translations file.

## Test Plan

No test required

## Related PRs and Issues

No

## Checklist

- [ ] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [ ] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

Yes

2024-05-22 17:19 UTC, stnguyen90 requested changes
@navjotNSK, thanks for raising this PR! Unfortunately a lot of the translations don't quite seem right and there are more translations than the 11 you've done.

2024-05-22 17:19 UTC, stnguyen90 commented on app/config/locale/translations/af.json
> +    "countries.hk": "Hongkong",
incorrect

2024-05-22 17:19 UTC, stnguyen90 commented on app/config/locale/translations/bg.json
> +    "countries.hk": "Хонконг",
Isn't this missing a space?

2024-05-23 10:27 UTC, navjotNSK commented on app/config/locale/translations/bg.json
> +    "countries.hk": "Хонконг",
space added and all files refactored.

2024-05-23 10:27 UTC, navjotNSK commented on app/config/locale/translations/af.json
> +    "countries.hk": "Hongkong",
corrected.

2024-05-23 22:17 UTC, stnguyen90 requested changes
Please fix the merge conflicts. Once done, re-request a review in the PR:

![image](https://github.com/appwrite/appwrite/assets/1477010/0790f250-957d-4d30-8784-350d18f73706)

2024-05-24 06:56 UTC, navjotNSK commented
@stnguyen90 Merge conflicts removed.

2024-06-04 23:53 UTC, stnguyen90 requested changes
some still seem wrong. would you please make sure to go through all of them and verify they're correct?

2024-06-04 23:53 UTC, stnguyen90 commented on app/config/locale/translations/bg.json
> +    "countries.hk": "Хонконг",
I don't see the space here.

2024-06-04 23:53 UTC, stnguyen90 commented on app/config/locale/translations/be.json
> +    "countries.hk": "Гонконг",
how'd you get this? It looks different than what I see online 🧐

2024-06-04 23:53 UTC, stnguyen90 commented on app/config/locale/translations/bs.json
> +    "countries.hk": "Hongkong",
Is this missing a space?

2024-06-10 21:19 UTC, xuelink commented on app/config/locale/translations/be.json
> +    "countries.hk": "Гонконг",
Ганконг should be.

2024-06-11 14:59 UTC, stnguyen90 approved these changes

2024-06-11 15:00 UTC, merged