Delete all user sessions on blocking a user
appwrite/appwrite pull request #8545
Opened 2024-08-16 08:46 UTC by SophieNguyen113

## What does this PR do?

This PR introduces updates to the Update user status API to include the functionality of deleting all sessions when a user is blocked. Previously, user sessions were not deleted, which caused issues when a different user attempted to sign in on the same device. The changes ensure that when a user's status is updated to blocked, all their active sessions are deleted, allowing a different user to sign in.

## Test Plan

1. **Verify User Existence**
   - Send a GET request to `/users/{userId}` and check for a 200 status code.

2. **Activate User**
   - PATCH `/users/{userId}/status` with `status: true`.
   - Verify response: status code 200 and body contains `status: true`.

3. **Block User**
   - PATCH `/users/{userId}/status` with `status: false`.
   - Verify response: status code 200 and body contains `status: false`.

4. **Check Session Deletion**
   - Verify no active sessions for the blocked user (if applicable).
   - GET `/users/{userId}` and check for `status: false`.

5. **Reactivate User**
   - PATCH `/users/{userId}/status` with `status: true`.
   - Verify response: status code 200 and body contains `status: true`.

## Checklist

- [x] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [x] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

2024-08-20 19:15 UTC, SophieNguyen113 commented
@stnguyen90  Hello, could you please give me permission for the workflows? Thanks.

2024-08-21 06:35 UTC, stnguyen90 requested changes
Tests seem to be failing. Have you tried running the tests locally?

2024-08-21 06:35 UTC, stnguyen90 commented on app/controllers/api/users.php
> +    ->label('usage.metric', 'users.{scope}.requests.update')
You can remove this. It's not used anymore.

2024-08-21 06:35 UTC, stnguyen90 commented on composer.lock
I don't think it was necessary to modify the composer.lock, right? If not, it would be best to leave it untouched.

2024-08-21 06:35 UTC, stnguyen90 commented on docs/references/users/update-user-status.md
> +Update the user status by its unique ID. This endpoint now includes functionality to delete all active sessions when a user is blocked, resolving issues when a different user attempts to sign in on t
> This endpoint now includes functionality

No need to say it "now includes functionality". Just state it as a fact.

2024-09-09 21:52 UTC, SophieNguyen113 commented
@stnguyen90  Hello, all the test cases were fixed. Please review. Thanks

2024-09-12 21:22 UTC, SophieNguyen113 commented
Since I accidentally messed up this PR, I would close it and open a new one. Thanks.

2024-09-12 21:22 UTC, closed without merging