fix refreshToken is missing from google oauth
appwrite/appwrite pull request #8864
Opened 2024-10-26 11:44 UTC by Shaik-Sirajuddin

## What does this PR do?
Query parameters are missing in google oauth login url , which are needed to get refreshToken from google oauth api
This PR fixes the issue #5987 by adding the necessary query params while building oauth url
(Provide a description of what this PR does and why it's needed.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Screenshots may also be helpful.)

- Enable Google OAUTH for your project from appwrite console
- use appwrite web ( or any client side  )  sdk  and make call to account.createOAuth2Session for login
- update session by calling account.updateSession
- You may see providerAccessToken is present in session object which was missing before the fix 

## Related PRs and Issues

- #5987 

## Checklist

- [x] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [ ] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

2024-11-01 15:35 UTC, Shaik-Sirajuddin commented
Before : 
Missing  _**_providerRefreshToken_**_ 
![Screenshot from 2024-11-01 20-52-36](https://github.com/user-attachments/assets/3f6e1c2a-3115-48f6-9c73-d4ec6a95b893)
Failed Update Session Request ( due to missing refresh token )
![cropped](https://github.com/user-attachments/assets/c9670947-2aec-4a0e-8a7b-28ecd86e11f0)

After : 
_**_providerRefreshToken_**_  is returned by google oauth , stored in session object
![Screenshot from 2024-11-01 20-52-11](https://github.com/user-attachments/assets/098a18ac-81dc-415b-b426-efeba564c3b2)

Successful update session request
![Screenshot from 2024-11-01 20-56-54](https://github.com/user-attachments/assets/c4ef3691-6ee5-4133-9e37-f0a11be22e46)

2024-12-20 20:36 UTC, stnguyen90 requested changes

2024-12-20 20:36 UTC, stnguyen90 commented on src/Appwrite/Auth/OAuth2/Google.php
> +            'prompt' => 'consent'
Do we have to add this `'prompt' => 'consent'`? If not, let's leave it out to avoid changing the behavior.
```suggestion
```

2025-02-19 17:00 UTC, stnguyen90 commented on src/Appwrite/Auth/OAuth2/Google.php
> +            'prompt' => 'consent'
@Shaik-Sirajuddin, question for you ☝️

2025-04-22 13:52 UTC, samssouza commented on src/Appwrite/Auth/OAuth2/Google.php
> +            'prompt' => 'consent'
That would be great. Consent screen don't seem to show otherwise for google

2025-04-22 16:35 UTC, stnguyen90 commented
Closing stale PR

2025-04-22 16:35 UTC, closed without merging