Added advanced topic section for contributors
appwrite/appwrite pull request #890
Opened 2021-02-09 12:37 UTC by eldadfux

## What does this PR do?

Added a new advanced topic section for contributors who wish to better understand the Appwrite design and codebase.

## Test Plan

N/A

## Related PRs and Issues

N/A

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2021-02-09 12:38 UTC, eldadfux commented
Please suggest other topics you think may be useful.

2021-02-09 13:08 UTC, TorstenDittmann commented
We could add https://en.wikipedia.org/wiki/OAuth as well 👍🏻

2021-02-09 13:22 UTC, eldadfux commented
> We could add https://en.wikipedia.org/wiki/OAuth as well 👍🏻

good one...

2021-02-09 13:35 UTC, TorstenDittmann approved these changes

2021-02-10 01:16 UTC, lohanidamodar requested changes

2021-02-10 01:16 UTC, lohanidamodar commented on CONTRIBUTING.md
> +We love to create issues that are good for begginers and label them as `good for begginers` or `hacktoberfest`, but some more advanced topics might require extra knowledge. Below is a list with links
*beginners not begginers

* Below is a list **with links which** you can use to learn more about some **of the more** advance topics that will help you master Appwrite codebase.

2021-02-10 15:08 UTC, kodumbeats commented
Maybe some literature about the frontend console? Possible suggestions:
- [MVVM](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93viewmodel)
- [Gulp](https://gulpjs.com/docs/en/getting-started/quick-start)

2021-02-19 08:35 UTC, eldadfux commented
Adapted the list according to all comments, feel free to submit new stuff at any time.

2021-02-19 08:35 UTC, merged