WIP: Add new console endpoint
appwrite/appwrite pull request #8970
Opened 2024-11-13 16:17 UTC by vermakhushboo

## What does this PR do?

Add new console endpoint to check for resource availability like subdomain etc.

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Screenshots may also be helpful.)

## Related PRs and Issues

- (Related PR or issue)

## Checklist

- [ ] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [ ] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

2024-11-13 18:36 UTC, eldadfux requested changes

2024-11-13 18:36 UTC, eldadfux commented on app/controllers/api/console.php
> +            throw new Exception(Exception::RULE_ALREADY_EXISTS, 'Subdomain already assigned to different resource.');
This error should be generic

2024-11-13 18:38 UTC, vermakhushboo commented on src/Appwrite/Platform/Modules/Sites/Http/Sites/CreateSite.php
> +            ->label('scope', 'functions.write')
Yes, WIP PR, will fix

2024-11-20 13:17 UTC, Meldiron commented on app/controllers/api/console.php
> +    ->desc('Check resource availability')
From what I remember, we use description for non-rest terminology. for example PATCH /builds has description "Redeploy", to explain it well.

2024-11-20 13:17 UTC, Meldiron commented on app/controllers/api/console.php
> +    ->label('sdk.response.model', Response::MODEL_NONE)
Lets add rate limits to this endpoint, pretty strict. 10 per minute?

2025-01-14 09:34 UTC, christyjacob4 commented on app/controllers/api/console.php
> +        }
you dont need this check, the validator already does this for you

2025-01-14 09:57 UTC, christyjacob4 commented on app/controllers/api/console.php
> +    ->action(function (string $resourceId, string $type, Response $response, Database $dbForConsole) {
this will allow the console to check resources that belong to other projects and users as well. is this expected ?

2025-01-14 10:02 UTC, christyjacob4 commented on app/controllers/api/console.php
> +        if ($document && !$document->isEmpty()) {
getDocument() always returns a document, we just need to check if the document is empty

2025-01-14 10:14 UTC, christyjacob4 commented on app/controllers/api/console.php
> +    ->label('scope', 'projects.read')
this is not a route that is accessed with an API key right? So there is no scope required

2025-01-14 10:19 UTC, christyjacob4 commented on app/controllers/api/console.php
> +    ->groups(['api', 'projects'])
Also why is this part of the console service? This is more suited to the projects' service

2025-01-23 13:13 UTC, vermakhushboo commented on app/controllers/api/console.php
> +    ->action(function (string $resourceId, string $type, Response $response, Database $dbForConsole) {
Yes, and that's why the endpoint doesn't return the document, just the status code to reflect whether the resource is present or not

2025-01-23 13:13 UTC, vermakhushboo commented on app/controllers/api/console.php
> +    ->label('scope', 'projects.read')
I'm not 100% sure about this. Do you think it should be a public endpoint? We can still add abuse checks if it's a public endpoint, right?

2025-01-23 13:15 UTC, vermakhushboo commented on app/controllers/api/console.php
> +    ->groups(['api', 'projects'])
Rules aren't created at a project level. They should be unique across Appwrite. The data is stored in `console` DB and thus, the endpoint is also added to console controller.

2025-01-23 18:32 UTC, christyjacob4 commented on app/controllers/api/console.php
> +    ->label('scope', 'projects.read')
I checked the code again and this looks correct 👍

2025-01-23 18:33 UTC, christyjacob4 approved these changes

2025-01-24 08:35 UTC, Meldiron commented on app/controllers/api/console.php
> +    ->label('abuse-key', 'userId:{userId}')
```suggestion
    ->label('abuse-key', 'userId:{userId},url:v1/console/resources/:resourceId')
```

2025-01-24 08:37 UTC, Meldiron commented on app/controllers/api/console.php
> +    ->label('abuse-key', 'userId:{userId}')
Add abuse-time to be 60

2025-01-24 08:37 UTC, Meldiron commented on app/controllers/api/console.php
> +    ->label('sdk.method', 'checkResourceAvailability')
```suggestion
    ->label('sdk.method', 'getResourceAvailability')
```

2025-01-24 08:39 UTC, Meldiron commented on app/controllers/api/console.php
> +    ->label('scope', 'projects.read')
Lets check with Christy scope for this endpoint. Maybe `sites.write` instead? (because we do it in that flow)

2025-01-24 08:45 UTC, Meldiron commented on app/controllers/api/console.php
> +            throw new Exception(Exception::RESOURCE_ALREADY_EXISTS, 'Resource ID is already in use.');
Let's avoid specific description here, it will be taken from errors.php

2025-02-06 08:48 UTC, Meldiron commented on app/controllers/api/console.php
> +            throw new Exception(Exception::RESOURCE_ALREADY_EXISTS);
Lets add E2E tests, including some faulure tests

2025-02-08 10:21 UTC, Meldiron commented on tests/e2e/Services/Sites/SitesCustomServerTest.php
> +        $ruleId1 = \md5($domain);
This logic could change in future, we shouldn't relay on it.
We can listRules for site we just created, and get rule ID that way.

2025-02-08 10:22 UTC, Meldiron commented on tests/e2e/Services/Sites/SitesCustomServerTest.php
> +        ]);
If we generate rule IDs in tests, it means we will need to generate them in Console, and doing md5 hash in Console doesn't sound right.
Can we accept domain directly for the availability check endpoint instead?

2025-02-08 10:23 UTC, Meldiron commented on tests/e2e/Services/Sites/SitesCustomServerTest.php
> +        sleep(1);
lets see if we can replace sleep with waitUntil instead

2025-02-11 12:31 UTC, Meldiron commented on src/Appwrite/Platform/Modules/Console/Http/Resources/Get.php
> +            ->setHttpPath('v1/console/resources/:resourceId')
```suggestion
            ->setHttpPath('v1/console/availabilities')
```

2025-02-11 12:36 UTC, Meldiron commented on src/Appwrite/Platform/Modules/Console/Http/Resources/Get.php
> +        return 'getResourceAvailability';
```suggestion
        return 'getResource';
```

2025-02-11 12:36 UTC, Meldiron commented on src/Appwrite/Platform/Modules/Console/Http/Resources/Get.php
> +            ->setHttpPath('v1/console/resources/:resourceId')
```suggestion
            ->setHttpPath('v1/console/resources')
```

2025-02-12 10:48 UTC, Meldiron commented on src/Appwrite/Platform/Modules/Console/Http/Resources/Get.php
> +        if ($type == 'rules') {
```suggestion
        if ($type === 'rules') {
```

2025-02-12 10:49 UTC, Meldiron commented on src/Appwrite/Platform/Modules/Console/Http/Resources/Get.php
> +        throw new Exception(Exception::GENERAL_ARGUMENT_INVALID, 'Invalid type');
```suggestion
	// Only occurs if type is added into whitelist, but not supported in action
        throw new Exception(Exception::GENERAL_ARGUMENT_INVALID);
```

2025-02-12 10:50 UTC, Meldiron commented on tests/e2e/Services/Sites/SitesCustomServerTest.php
> +        $this->assertEquals('Test Site', $site['body']['name']);
Let's setupSite instead. We should only do createSite, if creation is purpose of the test.

2025-02-12 10:51 UTC, Meldiron commented on tests/e2e/Services/Sites/SitesCustomServerTest.php
> +        $domain = $rule['body']['rules'][0]['domain'];
We now have `$this->getSitDomain()` to simplify this

2025-02-12 10:51 UTC, Meldiron commented on tests/e2e/Services/Sites/SitesCustomServerTest.php
> +            $this->assertEmpty($rule['body']['rules']);
We can also assert that 'total' equals 0

2025-02-12 16:05 UTC, Meldiron approved these changes

2025-02-12 16:17 UTC, merged