Fix outdated CLI commands in documentation
appwrite/appwrite pull request #9122
Opened 2024-12-20 17:13 UTC by gurjeetsinghvirdee

## What does this PR do?

- It replaces the `deploy` command with a `push`
- It fixes the outdated create document command to resolve errors users might encounter.

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Screenshots may also be helpful.)

## Related PRs and Issues

- appwrite/sdk-for-cli#152

## Checklist

- [x] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [x] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

2025-01-05 19:39 UTC, stnguyen90 requested changes

2025-01-05 19:39 UTC, stnguyen90 commented on docs/sdks/cli/GETTING_STARTED.md
> +$ appwrite databases create-document --database-id=<DATABASE_ID> --collection-id=<COLLECTION_ID> --document-id="unique()" --data '{"name": "Walter O Brein"}'
Let's keep the permissions example too for an example on how to pass array values

2025-01-05 20:00 UTC, gurjeetsinghvirdee commented on docs/sdks/cli/GETTING_STARTED.md
> +$ appwrite databases create-document --database-id=<DATABASE_ID> --collection-id=<COLLECTION_ID> --document-id="unique()" --data '{"name": "Walter O Brein"}'
Re-added the perms

2025-01-23 02:03 UTC, stnguyen90 commented on docs/sdks/cli/GETTING_STARTED.md
> +$ appwrite databases create-document --database-id=<DATABASE_ID> --collection-id=<COLLECTION_ID> --document-id="unique()" --data '{"name": "Walter O Brein"}' --permissions 'read("any")' 'read("team:a
i don't think the = should be there, right?

2025-02-19 17:38 UTC, stnguyen90 approved these changes

2025-02-21 21:59 UTC, merged