fix-missing-port-on-url
appwrite/appwrite pull request #917
Opened 2021-02-18 11:57 UTC by lohanidamodar

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2021-02-18 14:23 UTC, eldadfux commented on app/views/layouts/default.phtml
> +    <meta property="og:image"  content="<?php echo $protocol; ?>://<?php echo $domain; ?><?php echo $port != 80 ?':'.$port : '' ?>/images/logo.png?v=<?php echo APP_CACHE_BUSTER; ?>" />
I think you can use here $endpoint instead, anyway missing a check for port 443

2021-02-18 14:24 UTC, eldadfux requested changes
1 minor fix

2021-02-18 16:43 UTC, lohanidamodar commented
@eldadfux done

2021-02-19 04:22 UTC, eldadfux approved these changes

2021-02-19 04:23 UTC, merged