Feat flutter sdk getting started
appwrite/appwrite pull request #981
Opened 2021-03-15 10:45 UTC by lohanidamodar

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2021-03-15 16:47 UTC, eldadfux approved these changes

2021-03-15 17:20 UTC, kodumbeats requested changes

2021-03-15 17:20 UTC, kodumbeats commented on docs/sdks/flutter/GETTING_STARTED.md
> +### Android
I got confused in the header hierarchy here: Why are the Android headers `h3` and iOS/Web `h4`?

2021-03-15 17:20 UTC, kodumbeats commented on docs/sdks/flutter/GETTING_STARTED.md
> +.setEndpoint('https://localhost/v1') // Your Appwrite Endpoint
Should this code be formatted with indentation? Not sure if that happens in the markdown file or somewhere else.

2021-03-16 10:57 UTC, kodumbeats approved these changes

2021-03-16 11:07 UTC, merged